In [78]:
import pandas as pd
import re

!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\maria\github_marianaarboleda\cp_backend\.conda\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\maria\github_marianaarboleda\cp_backend\.conda\lib\site-packages (from openpyxl) (2.0.0)

In [79]:
base = pd.read_excel("../data/limpieza/observacionesstem_post.xlsx", skiprows=[0])
base

c:\Users\maria\Github_marianaarboleda\cp_backend\.conda\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Fecha de inicio,Fecha de finalización,Tipo de respuesta,Dirección IP,Progreso,Duración (en segundos),Finalizado,Fecha registrada,ID de respuesta,Apellido del destinatario,...,¿Están los/las estudiantes trabajando individualmente?.11,¿Están los/las estudiantes trabajando en parejas o grupos?.11,¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?.11,"¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?.11","Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase.11",Timing - Primer clic.12,Timing - Último clic.12,Timing - Envío de página.12,Timing - Recuento de clics.12,"Por favor, seleccione qué desea hacer."
0,2025-09-22 08:06:33,2025-09-22 09:18:25,IP Address,191.156.45.69,100,4312,True,2025-09-22 09:18:26.321,R_5iF6jTr3hvUIYHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-09-18 09:16:32,2025-09-18 09:16:38,IP Address,190.71.179.101,0,5,False,2025-09-25 09:16:38.789,R_7eFrNoPojYNZklD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-09-22 09:13:04,2025-09-22 09:13:11,IP Address,191.156.15.211,0,7,False,2025-09-29 09:13:19.283,R_3zcXeJRKsLtIdAl,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-10-03 11:40:00,2025-10-03 12:48:28,IP Address,181.129.209.170,80,4107,False,2025-10-10 12:48:30.632,R_3eaFJ8Fkk7IfiDm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-10-27 11:16:06,2025-10-27 12:13:34,IP Address,191.156.43.153,100,3448,True,2025-10-27 12:13:35.297,R_31dqVm3EeEdIJqi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2025-10-29 07:11:52,2025-10-29 08:34:42,IP Address,191.156.43.127,100,4970,True,2025-10-29 08:34:43.630,R_310nLwVtnbAjLFy,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2025-11-05 08:55:04,2025-11-05 09:45:20,IP Address,191.156.9.141,100,3015,True,2025-11-05 09:45:21.075,R_7X70SCcie932mQx,NaN,...,NaN,NaN,NaN,NaN,NaN,8.955,8.955,8.967,1.0,Ir a las preguntas de cierre de la clase
7,2025-11-06 10:50:53,2025-11-06 13:10:47,IP Address,191.95.149.132,100,8394,True,2025-11-06 13:10:48.470,R_1EWNOwR7k9SdwrL,NaN,...,Ninguno,Todos(as),No se evidencian roles de liderazgo,Ninguno,Un representante de cada grupo se encuetnra so...,9.381,351.325,351.342,45.0,Ir a las preguntas de cierre de la clase
8,2025-11-13 11:10:09,2025-11-13 12:09:21,IP Address,190.130.109.158,100,3552,True,2025-11-13 12:09:22.420,R_7Oe7ZAcrnQzWtoh,NaN,...,Ninguno,Todos(as),Niños y niñas por igual,Ninguno,La docente esa lanzando la pregunta a los estu...,60.626,230.330,230.343,36.0,Regresar al bloque de preguntas generales

In [80]:
df = base.copy()

In [81]:
df.columns.tolist()

['Fecha de inicio',
 'Fecha de finalización',
 'Tipo de respuesta',
 'Dirección IP',
 'Progreso',
 'Duración (en segundos)',
 'Finalizado',
 'Fecha registrada',
 'ID de respuesta',
 'Apellido del destinatario',
 'Nombre del destinatario',
 'Correo electrónico del destinatario',
 'Referencia a datos externos',
 'Latitud de la ubicación',
 'Longitud de la ubicación',
 'Canal de la distribución',
 'Idioma del usuario',
 'Fecha del acompañamiento\n\nIndique la fecha en que realizó el acompañamiento en aula.\n\nUse el formato dd/mm/aaaa',
 'Hora de inicio de la clase (Formato Hora Militar)\n\nIndique la hora en la que inició la clase acompañada.',
 'Seleccione la institución educativa y docente a observar - Mentor',
 'Seleccione la institución educativa y docente a observar - Institución Educativa',
 'Seleccione la institución educativa y docente a observar - Nombre del/la docente observado',
 'Número de documento de docente observado',
 'Indique sexo del docente',
 'Asignatura - Selected Choice',
 'Asignatura - Otra - Texto',
 'Grado',
 '¿El/la docente trabaja con una guía pedagógica?',
 '¿A qué grado corresponde la guía pedagógica empleada?',
 '¿Con qué número de guía se trabaja?',
 '¿Con qué sesión de la guía se trabaja?',
 'Tema de la clase\n\nSi no se trabaja con una guía pedagógica, por favor indique el tema de la clase',
 'Número de estudiantes en total\n\nNúmero entero sin puntos',
 'Número de estudiantes de sexo femenino\n\nNúmero entero sin puntos',
 'Número de estudiantes de sexo masculino\n\nNúmero entero sin puntos',
 'Duración estimada de la clase (horas y minutos)\n\nPor favor escriba el tiempo estimado que debe durar la clase observada en formato horas y minutos (00:00). Por ejemplo, si la clase dura 50 minutos, debe colocar 00:50.',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Computadores portátiles',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Computadores de escritorio',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Tabletas',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Celulares',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Tarjetas micro:bit',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Video proyector (Video Beam)',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - No se hizo uso de tecnologías digitales',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Otra',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Otra - Texto',
 'Timing - Primer clic',
 'Timing - Último clic',
 'Timing - Envío de página',
 'Timing - Recuento de clics',
 'Al inicio de la clase\n\n\n\n¿Cuántos minutos transcurren entre la hora de inicio y el momento en que el docente empieza a gestionar el aula para empezar la clase? Escriba la cantidad de minutos en números enteros.\n\nNota: Las actividades gestión inicial como llamar a lista o seguir rutinas de inicio establecidas, se consideran parte de la clase.',
 '¿Se presentan los objetivos de aprendizaje de la lección?',
 '¿Se exploran los conocimientos previos de los estudiantes y su conexión con los temas de la lección?',
 '¿Se presentan claramente los conceptos claves que serán usados en la lección?',
 'Actividades que promueven subhabilidades del pensamiento computacional\n\n\n\n¿Se realizan actividades que promueven el uso de abstracción, descomposición, pensamiento lógico, pensamiento algorítmico, depuración o reconocimiento de patrones por parte de los/las estudiantes?\n\nMarque sí, si en la clase se realiza alguna actividad práctica de la asignatura que busque promover alguna de las 6 subhabilidades del pensamiento computacional. Ej. En clase de matemáticas se pide a los a los/las estudiantes que sigan una secuencia de pasos específica para realizar una tarea (algoritmia) o que analicen la solución de un ejercicio a fin de encontrar algún error que se haya cometido durante el proceso (depuración).',
 'Fomento de las subhabilidades del pensamiento computacional\n\n\n\nResponda todas las preguntas y luego, si es posible, describa brevemente la actividad que se realizó en el aula y que permitió promover el uso de las subhabilidades de pensamiento computacional.\n\n\n\nDescomposición: ¿Durante la clase se realizan actividades que requieren descomponer un problema o proceso en partes más pequeñas?\n\nEj. Se pide a los estudiantes que planteen las actividades generales que desarrollarán en cada etapa del método científico, antes de proponer y ejecutar un experimento.',
 'Reconocimiento de patrones: ¿Los/las estudiantes realizan actividades para encontrar patrones y relaciones entre elementos?\n\nEj. Se pide a los/las estudiantes analizar las células animal y vegeta y luego crear un listado de las características comunes y las diferencias entre ellas.',
 'Pensamiento algorítmico: ¿La/El docente invita a los/las estudiantes a organizar y/o ejecutar una secuencia de pasos para llevar a cabo una tarea?\n\nEj. Se entrega a los/las estudiantes un laboratorio de física que requiere el desarrollo secuencial de ciertas actividades y se monitorea el avance.',
 'Depuración: ¿La/El docente solicita a los/las estudiantes identificar y corregir errores en la ejecución de un proceso o tarea?\n\nEj. Se pide a los/las estudiantes intercambiar sus respuestas a un taller, marcar las fallas detectadas en el trabajo de sus compañeros y darles una recomendación escrita sobre lo que deben hacer para corregirlas.',
 'Abstracción: ¿Se solicita a las/los estudiantes identificar la información relevante sobre un tema y/o sintetizarla?\n\nEj. Se presenta un problema situacional matemático y se pide a los/las estudiantes leer atentamente el enunciado y plantear la ecuación para solucionarlo.',
 'Pensamiento lógico: ¿Se requiere que las/los estudiantes evalúen si se cumplen o no algunas condiciones y/o que realicen tareas o tomen decisiones a partir de los resultados de esta evaluación?\n\nEj. Se presenta a los estudiantes un listado de hábitos diarios para que los analicen y determinen cuáles de ellos podrían afectar positiva o negativamente al sistema excretor.',
 'Por favor, mencione las actividades que se realizaron en la clase acompañada, que a su juicio, contribuyen al desarrollo de una o más subhabilidades del pensamiento computacional de los/las estudiantes.',
 'Prácticas de Pensamiento Computacional - parte 1\n\n¿Se observan prácticas de datos?\n\nMarque sí si en la clase se recopilan datos mediante generan o recolectan datos haciendo uso de herramientas computacionales, organización y clasificación de datos, análisis de los patrones existentes en los datos, o si se generan tablas o gráficos a partir de datos.',
 'Prácticas de Datos\n\n¿Durante la clase se realizan actividades para recolectar datos con herramientas tecnológicas?\n\nEj. Se utiliza la micro:bit para recolectar datos de temperatura o se ingresan registros de observaciones en una hoja de cálculo para hacerles posterior análisis.',
 '¿Los/las estudiantes realizan actividades para encontrar patrones y relaciones en conjuntos de datos?\n\nEj. hacen conteo de frecuencias y las comparan, o hacen análisis de medias y tendencias.',
 '¿La/El docente invita a los/las estudiantes a organizar y clasificar datos?\n\nEj. Se pide a los/las estudiantes organizar los registros de observaciones de mayor a menor para identificar valores máximos y mínimos.',
 '¿La/El docente propone realizar tablas, graficas o diagramas con los datos?\n\nEj. Se pide a los/las estudiantes hacer una gráfica de barras o crear un gráfico estadístico utilizando herramientas de una hoja de cálculo o de forma desconectada',
 'Por favor, mencione las actividades asociadas a las prácticas de datos que se hayan desarrollado en la clase acompañada.',
 'Prácticas de Pensamiento Computacional - parte 2\n\n\n\n¿Se observan prácticas de programación?\n\nMarque sí si en la clase se invita a los/las estudiantes a dividir un problema en otros más pequeños, si se crean instrucciones paso a paso para resolver un problema, si se codifica (en bloques o en texto), o si se prueban y evalúan los resultados de una posible solución a fin de plantear mejoras.',
 'Programación\n\n\n\n\n¿Los/las estudiantes realizan actividades que implican descomponer los problemas en partes más pequeñas?',
 '¿Los/las estudiantes crean instrucciones paso a paso para resolver un problema?',
 '¿Los/las estudiantes utilizan un lenguaje de programación para codificar la solución a un problema?',
 '¿Los/las estudiantes ejecutan, depuran, y hacen ajustes o mejoras a sus programas?',
 'Por favor, mencione las actividades asociadas a programación que se hayan desarrollado en la clase acompañada.',
 'Prácticas de Pensamiento Computacional - parte 3\n\n\n¿Se observa el uso de simulaciones computacionales?\n\nMarque sí si en la clase se hace uso de aplicaciones interactivas para entender o probar fenómenos científicos o del mundo físico, o si se discuten las limitaciones que tienen una simulación en contraste con las condiciones del mundo real.',
 'Simulaciones\n\n¿Los/las estudiantes usan simuladores computacionales?',
 '¿La/El docente brinda espacios para que los/las estudiantes evalúen las simulaciones computacionales?\n\nEj. se les invita a considerar si hay otros factores que pudieran agregarse o modificarse para hacer una simulación más precisa que lo que permite la herramienta.',
 'Por favor, mencione las actividades asociadas a simulaciones computacionales que se hayan desarrollado en la clase acompañada.',
 'Prácticas de Pensamiento Computacional - parte 4\n\n\n\n¿Se observan prácticas asociadas al Pensamiento Sistémico?\n\nMarque sí si en la clase los/las estudiantes logran identificar las partes de un todo que son cuantificables, si logran identificar las relaciones numéricas entre diferentes partes de un sistema, o si logran identificar cómo el incremento de un factor tiene impacto en el incremento o decremento de otro elemento del sistema.',
 'Pensamiento sistémico\n\n\n¿La/El docente realiza actividades que permiten a los/las estudiantes identificar datos numéricos?\n\nEj. En una simulación sobre la cantidad de lluvia que cae en la ciudad, se invita a los/las estudiantes a considerar que las cifras se miden en milímetros cúbicos y corresponden a litros de agua por metro cuadrado',
 '¿Los/las estudiantes identifican las relaciones numéricas dentro de un sistema?\n\nEj. Los/las estudiantes analizan lo que sucede con los depredadores si se cambian los valores iniciales de las presas o del alimento disponible para estas, en una simulación presa-depredador.',
 '¿Los/las estudiantes analizan cómo los cambios en las variables contribuyen a los resultados del sistema?\n\nEj. Los estudiantes determinan qué pasa, repetición a repetición de una simulación, cuando se incrementa en 1 el número inicial de depredadores.',
 'Por favor, mencione las actividades asociadas a pensamiento sistémico que se hayan desarrollado en la clase acompañada.',
 'Ciudadanía digital y comprensión y uso de la IA\n\n\n¿Se observan prácticas que busquen fomentar habilidades de ciudadanía digital o promover la comprensión y el uso de la IA?\n\n\nMarque sí si en la clase los/las estudiantes aprenden conceptos básicos de Inteligencia Artificial  (IA, aprendizaje automático, modelo, algoritmo de aprendizaje, datos de entrenamiento, predicción, sesgos, etc.), realizan actividades desconectadas o conectadas de IA, o analizan problemas de seguridad, éticos y de sesgos asociados al uso de la tecnología con o sin IA.',
 'Ciudadanía digital y comprensión y uso de la IA\n\nResponda todas las preguntas y luego, si es posible, describa brevemente la actividad que se realizó durante la clase y que permitió evidenciar el acercamiento a la comprensión y uso de la Inteligencia Artificial por parte de los/las estudiantes.\n\n\n¿Los/las estudiantes llevan a cabo alguna actividad desconectada para fortalecer su comprensión de conceptos de IA?\n\nEjemplo: analizar aplicaciones u objetos y decidir si corresponden o no a ejemplos de IA, etiquetar imágenes y luego discutir sesgos en la interpretación de estas, determinar los datos de entrenamiento requeridos para alguna toma de decisión o predicción, etc).',
 '¿Los/las estudiantes usan herramientas de IA generativa?\nEjemplo: hacen una consulta a un modelo grande de lenguaje como ChatGPT, crean imágenes mediante un prompt en Copilot o Meta, generan un video con Canva, etc.',
 '¿Los/las estudiantes entrenan modelos de IA o hacen uso de uno de estos modelos?\nEjemplo: crean un modelo de reconocimiento de imágenes con TeachableMachine, crean un modelo de reconocimiento de texto con https://machinelearningforkids.co.uk/, vinculan un modelo de IA creado a un programa de Scratch o vinculan un proyecto en MakeCode con un modelo de IA usando https://makeairobots.com/, etc.',
 '¿Se realizan discusiones críticas sobre perspectiva, sesgos algorítmicos, o la necesidad de que población diversa contribuya en proyectos computacionales?\nEjemplo: se analizan las fallas de un modelo de IA para reconocer una imagen, se discute por qué un modelo de IA genera imágenes que representan un estereotipo, se comentan las ventajas de que varias personas distintas colaboren para entrenar un modelo de IA, etc',
 '¿Se discuten o promueven buenas prácticas de seguridad digital (ej. la protección de datos, contraseñas, y el uso seguro de internet)?',
 '¿Se abordan aspectos éticos del uso de tecnologías digitales (ej. respeto a la privacidad, uso responsable de la información)?',
 'Por favor, mencione las actividades asociadas a ciudadanía digital (seguridad informática, uso ético de tecnologías, equidad ) y/o de IA que se hayan desarrollado en la clase acompañada.',
 'Sobre los conocimientos técnicos del docente\n\n\n¿Se usa el vocabulario adecuado (terminología correcta) con relación al pensamiento computacional ?\n\nDiligencie esta parte durante la observación, y si es preciso, ajuste respuestas dadas previamente para responder mejor a la generalidad de lo observado',
 '¿Se conectan los temas presentados con la vida diaria?',
 '¿Sabe cómo resolver los problemas técnicos cuando fallan las herramientas computacionales en el aula?',
 'Si aplica, por favor, indique las dificultades técnicas que se presentaron durante la clase acompañada',
 'Sobre las prácticas pedagógicas y de gestión de aula\n\n\n\n¿Se preparó de forma previa el material requerido para la lección?',
 '¿Se gestionan correctamente los materiales e instrumentos para el desarrollo de las actividades propuestas?',
 '¿Se valora el esfuerzo de los estudiantes para desarrollar las actividades propuestas?',
 '¿Se observa acompañamiento con estrategias de apoyo (aclaración de dudas, explicaciones, ejemplos adicionales, invitación a revisar notas de clases previas, etc) a los estudiantes durante el desarrollo de las actividades?',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se corrigen comentarios y comportamientos sexistas',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se estimula el liderazgo femenino',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se realizan acciones afirmativas en términos de género',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se dedica tiempo de la clase a hacer reflexiones sobre equidad de género, por ejemplo, destacando los aportes de personajes masculinos y femeninos',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se hace uso de lenguaje inclusivo, sin estereotipos de género, que promueva respeto por la diversidad',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - No se observa ninguna práctica pedagógica en pro de la equidad de género',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Otra',
 'Otra',
 'Por favor, agregue cualquier otra información adicional que considere relevante para aclarar sus respuestas a la pregunta anterior',
 'Instantánea 1 - minuto 8 de la observación\n\n\n\n¿Qué está haciendo el/la docente ahora?\n\nIndique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.',
 'Indique con quiénes está interactuando el/la docente',
 '¿Con quiénes está interactuando el/la docente?',
 '¿Están los/las estudiantes respondiendo las preguntas y/o participando en las discusiones?',
 '¿Están los/las estudiantes escuchando atentamente al docente?',
 '¿Están los/las estudiantes tomando nota de las explicaciones o discusiones?',
 '¿Están los/las estudiantes haciendo preguntas y/o pidiendo ayuda al docente?',
 '¿Están los/las estudiantes socializando su trabajo?',
 '¿Quiénes están socializando su trabajo?',
 '¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?',
 '¿Quiénes no están involucrados en las actividades que lidera el/la docente?',
 '¿Están haciendo uso de herramientas computacionales?',
 '¿Quiénes están haciendo uso de herramientas computacionales?',
 '¿Están los/las estudiantes trabajando individualmente?',
 '¿Están los/las estudiantes trabajando en parejas o grupos?',
 '¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?',
 '¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?',
 'Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase',
 '¿Avanzar a la Instantánea 2?',
 'Timing - Primer clic.1',
 'Timing - Último clic.1',
 'Timing - Envío de página.1',
 'Timing - Recuento de clics.1',
 'Instantánea 2 - minuto 13 de la observación\n\n\n\n¿Qué está haciendo el/la docente ahora?\n\nIndique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.',
 'Indique con quiénes está interactuando el/la docente.1',
 '¿Con quiénes está interactuando el/la docente?.1',
 '¿Están los/las estudiantes respondiendo las preguntas y/o participando en las discusiones?.1',
 '¿Están los/las estudiantes escuchando atentamente al docente?.1',
 '¿Están los/las estudiantes tomando nota de las explicaciones o discusiones?.1',
 '¿Están los/las estudiantes haciendo preguntas y/o pidiendo ayuda al docente?.1',
 '¿Están los/las estudiantes socializando su trabajo?.1',
 '¿Quiénes están socializando su trabajo?.1',
 '¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?.1',
 '¿Quiénes no están involucrados en las actividades que lidera el/la docente?.1',
 '¿Están haciendo uso de herramientas computacionales?.1',
 '¿Quiénes están haciendo uso de herramientas computacionales?.1',
 '¿Están los/las estudiantes trabajando individualmente?.1',
 '¿Están los/las estudiantes trabajando en parejas o grupos?.1',
 '¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?.1',
 '¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?.1',

In [82]:
df = df.loc[(df["Finalizado"] == True) | (df["Progreso"] > 80), :]

In [83]:
df = df.loc[df["Tipo de respuesta"] != "Survey Preview", :]

In [84]:
df["Fecha"] = df["Fecha del acompañamiento\n\nIndique la fecha en que realizó el acompañamiento en aula.\n\nUse el formato dd/mm/aaaa"].replace("-", "/", regex=True).replace("2925", '2025', regex=True)
df["Fecha"] = pd.to_datetime(df["Fecha"], errors="raise", dayfirst=True)
df = df[df['Fecha'] > pd.to_datetime('2025-04-01')]

In [85]:
df

,Fecha de inicio,Fecha de finalización,Tipo de respuesta,Dirección IP,Progreso,Duración (en segundos),Finalizado,Fecha registrada,ID de respuesta,Apellido del destinatario,...,¿Están los/las estudiantes trabajando en parejas o grupos?.11,¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?.11,"¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?.11","Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase.11",Timing - Primer clic.12,Timing - Último clic.12,Timing - Envío de página.12,Timing - Recuento de clics.12,"Por favor, seleccione qué desea hacer.",Fecha
0,2025-09-22 08:06:33,2025-09-22 09:18:25,IP Address,191.156.45.69,100,4312,True,2025-09-22 09:18:26.321,R_5iF6jTr3hvUIYHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-22
4,2025-10-27 11:16:06,2025-10-27 12:13:34,IP Address,191.156.43.153,100,3448,True,2025-10-27 12:13:35.297,R_31dqVm3EeEdIJqi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-10-27
5,2025-10-29 07:11:52,2025-10-29 08:34:42,IP Address,191.156.43.127,100,4970,True,2025-10-29 08:34:43.630,R_310nLwVtnbAjLFy,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-10-29
6,2025-11-05 08:55:04,2025-11-05 09:45:20,IP Address,191.156.9.141,100,3015,True,2025-11-05 09:45:21.075,R_7X70SCcie932mQx,NaN,...,NaN,NaN,NaN,NaN,8.955,8.955,8.967,1.0,Ir a las preguntas de cierre de la clase,2025-11-05
7,2025-11-06 10:50:53,2025-11-06 13:10:47,IP Address,191.95.149.132,100,8394,True,2025-11-06 13:10:48.470,R_1EWNOwR7k9SdwrL,NaN,...,Todos(as),No se evidencian roles de liderazgo,Ninguno,Un representante de cada grupo se encuetnra so...,9.381,351.325,351.342,45.0,Ir a las preguntas de cierre de la clase,2025-11-06
8,2025-11-13 11:10:09,2025-11-13 12:09:21,IP Address,190.130.109.158,100,3552,True,2025-11-13 12:09:22.420,R_7Oe7ZAcrnQzWtoh,NaN,...,Todos(as),Niños y niñas por igual,Ninguno,La docente esa lanzando la pregunta a los estu...,60.626,230.330,230.343,36.0,Regresar al bloque de preguntas generales,2025-11-13

In [86]:
#- Visita 1 = [abril-mayo]
#- visita 2 = [junio-julio]
#- visita 3 = [sept-nov]
# Keep only latest row per visita per Número de documento de docente observado/a

visita_dates = [
    (1, "2025-04-01", "2025-05-31"),
    (2, "2025-06-01", "2025-07-31"),
    (3, "2025-09-01", "2025-11-30"),
]
# Fecha del acompañamiento Indique la fecha en que realizó el acompañamiento en aula. Use el formato dd/mm/aaaa
# "19-03-2025" or "19/03/2025"
df["Fecha"] = df["Fecha del acompañamiento\n\nIndique la fecha en que realizó el acompañamiento en aula.\n\nUse el formato dd/mm/aaaa"].replace("-", "/", regex=True).replace("2925", '2025', regex=True)
df["Fecha"] = pd.to_datetime(df["Fecha"], errors="raise", dayfirst=True)
df = df[df['Fecha'] >= pd.to_datetime('2025-04-01')]
df["Visita"] = '2'


# for visita, start_date, end_date in visita_dates:
#     mask = (df["Fecha"] >= start_date) & (df["Fecha"] <= end_date)
#     df.loc[mask, "Visita"] = visita

df = df.sort_values(by=["Número de documento de docente observado", "Fecha de finalización"], ascending=False)
df = df.drop_duplicates(subset=["Número de documento de docente observado", "Visita"], keep="first")

df.dropna(subset=['Visita'], inplace=True)

In [87]:
# Keep only last 2 per docente (Número de documento de docente observado), assign the column Momento (Pre o Post)
df = df.sort_values(by=["Número de documento de docente observado", "Fecha"], ascending=[True, False])
df = df.groupby("Número de documento de docente observado").head(2).reset_index(drop=True)
df = df.sort_values(by=["Número de documento de docente observado", "Fecha"], ascending=[True, True])
df["Momento"] = 'Post'#df.groupby("Número de documento de docente observado").cumcount().map({0: "Pre", 1: "Post"})

# Remove observations with only one Momento
#df = df.groupby('Número de documento de docente observado').filter(lambda x: x['Momento'].nunique() > 1)

In [88]:
df

,Fecha de inicio,Fecha de finalización,Tipo de respuesta,Dirección IP,Progreso,Duración (en segundos),Finalizado,Fecha registrada,ID de respuesta,Apellido del destinatario,...,"¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?.11","Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase.11",Timing - Primer clic.12,Timing - Último clic.12,Timing - Envío de página.12,Timing - Recuento de clics.12,"Por favor, seleccione qué desea hacer.",Fecha,Visita,Momento
0,2025-09-22 08:06:33,2025-09-22 09:18:25,IP Address,191.156.45.69,100,4312,True,2025-09-22 09:18:26.321,R_5iF6jTr3hvUIYHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-22,2,Post
1,2025-11-13 11:10:09,2025-11-13 12:09:21,IP Address,190.130.109.158,100,3552,True,2025-11-13 12:09:22.420,R_7Oe7ZAcrnQzWtoh,NaN,...,Ninguno,La docente esa lanzando la pregunta a los estu...,60.626,230.330,230.343,36.0,Regresar al bloque de preguntas generales,2025-11-13,2,Post
2,2025-10-27 11:16:06,2025-10-27 12:13:34,IP Address,191.156.43.153,100,3448,True,2025-10-27 12:13:35.297,R_31dqVm3EeEdIJqi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-10-27,2,Post
3,2025-10-29 07:11:52,2025-10-29 08:34:42,IP Address,191.156.43.127,100,4970,True,2025-10-29 08:34:43.630,R_310nLwVtnbAjLFy,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-10-29,2,Post
4,2025-11-05 08:55:04,2025-11-05 09:45:20,IP Address,191.156.9.141,100,3015,True,2025-11-05 09:45:21.075,R_7X70SCcie932mQx,NaN,...,NaN,NaN,8.955,8.955,8.967,1.0,Ir a las preguntas de cierre de la clase,2025-11-05,2,Post
5,2025-11-06 10:50:53,2025-11-06 13:10:47,IP Address,191.95.149.132,100,8394,True,2025-11-06 13:10:48.470,R_1EWNOwR7k9SdwrL,NaN,...,Ninguno,Un representante de cada grupo se encuetnra so...,9.381,351.325,351.342,45.0,Ir a las preguntas de cierre de la clase,2025-11-06,2,Post

In [89]:
df.columns.tolist()

['Fecha de inicio',
 'Fecha de finalización',
 'Tipo de respuesta',
 'Dirección IP',
 'Progreso',
 'Duración (en segundos)',
 'Finalizado',
 'Fecha registrada',
 'ID de respuesta',
 'Apellido del destinatario',
 'Nombre del destinatario',
 'Correo electrónico del destinatario',
 'Referencia a datos externos',
 'Latitud de la ubicación',
 'Longitud de la ubicación',
 'Canal de la distribución',
 'Idioma del usuario',
 'Fecha del acompañamiento\n\nIndique la fecha en que realizó el acompañamiento en aula.\n\nUse el formato dd/mm/aaaa',
 'Hora de inicio de la clase (Formato Hora Militar)\n\nIndique la hora en la que inició la clase acompañada.',
 'Seleccione la institución educativa y docente a observar - Mentor',
 'Seleccione la institución educativa y docente a observar - Institución Educativa',
 'Seleccione la institución educativa y docente a observar - Nombre del/la docente observado',
 'Número de documento de docente observado',
 'Indique sexo del docente',
 'Asignatura - Selected Choice',
 'Asignatura - Otra - Texto',
 'Grado',
 '¿El/la docente trabaja con una guía pedagógica?',
 '¿A qué grado corresponde la guía pedagógica empleada?',
 '¿Con qué número de guía se trabaja?',
 '¿Con qué sesión de la guía se trabaja?',
 'Tema de la clase\n\nSi no se trabaja con una guía pedagógica, por favor indique el tema de la clase',
 'Número de estudiantes en total\n\nNúmero entero sin puntos',
 'Número de estudiantes de sexo femenino\n\nNúmero entero sin puntos',
 'Número de estudiantes de sexo masculino\n\nNúmero entero sin puntos',
 'Duración estimada de la clase (horas y minutos)\n\nPor favor escriba el tiempo estimado que debe durar la clase observada en formato horas y minutos (00:00). Por ejemplo, si la clase dura 50 minutos, debe colocar 00:50.',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Computadores portátiles',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Computadores de escritorio',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Tabletas',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Celulares',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Tarjetas micro:bit',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Video proyector (Video Beam)',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - No se hizo uso de tecnologías digitales',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Selected Choice - Otra',
 'Tecnologías digitales disponibles en la clase\n\nElija todas las que apliquen - Otra - Texto',
 'Timing - Primer clic',
 'Timing - Último clic',
 'Timing - Envío de página',
 'Timing - Recuento de clics',
 'Al inicio de la clase\n\n\n\n¿Cuántos minutos transcurren entre la hora de inicio y el momento en que el docente empieza a gestionar el aula para empezar la clase? Escriba la cantidad de minutos en números enteros.\n\nNota: Las actividades gestión inicial como llamar a lista o seguir rutinas de inicio establecidas, se consideran parte de la clase.',
 '¿Se presentan los objetivos de aprendizaje de la lección?',
 '¿Se exploran los conocimientos previos de los estudiantes y su conexión con los temas de la lección?',
 '¿Se presentan claramente los conceptos claves que serán usados en la lección?',
 'Actividades que promueven subhabilidades del pensamiento computacional\n\n\n\n¿Se realizan actividades que promueven el uso de abstracción, descomposición, pensamiento lógico, pensamiento algorítmico, depuración o reconocimiento de patrones por parte de los/las estudiantes?\n\nMarque sí, si en la clase se realiza alguna actividad práctica de la asignatura que busque promover alguna de las 6 subhabilidades del pensamiento computacional. Ej. En clase de matemáticas se pide a los a los/las estudiantes que sigan una secuencia de pasos específica para realizar una tarea (algoritmia) o que analicen la solución de un ejercicio a fin de encontrar algún error que se haya cometido durante el proceso (depuración).',
 'Fomento de las subhabilidades del pensamiento computacional\n\n\n\nResponda todas las preguntas y luego, si es posible, describa brevemente la actividad que se realizó en el aula y que permitió promover el uso de las subhabilidades de pensamiento computacional.\n\n\n\nDescomposición: ¿Durante la clase se realizan actividades que requieren descomponer un problema o proceso en partes más pequeñas?\n\nEj. Se pide a los estudiantes que planteen las actividades generales que desarrollarán en cada etapa del método científico, antes de proponer y ejecutar un experimento.',
 'Reconocimiento de patrones: ¿Los/las estudiantes realizan actividades para encontrar patrones y relaciones entre elementos?\n\nEj. Se pide a los/las estudiantes analizar las células animal y vegeta y luego crear un listado de las características comunes y las diferencias entre ellas.',
 'Pensamiento algorítmico: ¿La/El docente invita a los/las estudiantes a organizar y/o ejecutar una secuencia de pasos para llevar a cabo una tarea?\n\nEj. Se entrega a los/las estudiantes un laboratorio de física que requiere el desarrollo secuencial de ciertas actividades y se monitorea el avance.',
 'Depuración: ¿La/El docente solicita a los/las estudiantes identificar y corregir errores en la ejecución de un proceso o tarea?\n\nEj. Se pide a los/las estudiantes intercambiar sus respuestas a un taller, marcar las fallas detectadas en el trabajo de sus compañeros y darles una recomendación escrita sobre lo que deben hacer para corregirlas.',
 'Abstracción: ¿Se solicita a las/los estudiantes identificar la información relevante sobre un tema y/o sintetizarla?\n\nEj. Se presenta un problema situacional matemático y se pide a los/las estudiantes leer atentamente el enunciado y plantear la ecuación para solucionarlo.',
 'Pensamiento lógico: ¿Se requiere que las/los estudiantes evalúen si se cumplen o no algunas condiciones y/o que realicen tareas o tomen decisiones a partir de los resultados de esta evaluación?\n\nEj. Se presenta a los estudiantes un listado de hábitos diarios para que los analicen y determinen cuáles de ellos podrían afectar positiva o negativamente al sistema excretor.',
 'Por favor, mencione las actividades que se realizaron en la clase acompañada, que a su juicio, contribuyen al desarrollo de una o más subhabilidades del pensamiento computacional de los/las estudiantes.',
 'Prácticas de Pensamiento Computacional - parte 1\n\n¿Se observan prácticas de datos?\n\nMarque sí si en la clase se recopilan datos mediante generan o recolectan datos haciendo uso de herramientas computacionales, organización y clasificación de datos, análisis de los patrones existentes en los datos, o si se generan tablas o gráficos a partir de datos.',
 'Prácticas de Datos\n\n¿Durante la clase se realizan actividades para recolectar datos con herramientas tecnológicas?\n\nEj. Se utiliza la micro:bit para recolectar datos de temperatura o se ingresan registros de observaciones en una hoja de cálculo para hacerles posterior análisis.',
 '¿Los/las estudiantes realizan actividades para encontrar patrones y relaciones en conjuntos de datos?\n\nEj. hacen conteo de frecuencias y las comparan, o hacen análisis de medias y tendencias.',
 '¿La/El docente invita a los/las estudiantes a organizar y clasificar datos?\n\nEj. Se pide a los/las estudiantes organizar los registros de observaciones de mayor a menor para identificar valores máximos y mínimos.',
 '¿La/El docente propone realizar tablas, graficas o diagramas con los datos?\n\nEj. Se pide a los/las estudiantes hacer una gráfica de barras o crear un gráfico estadístico utilizando herramientas de una hoja de cálculo o de forma desconectada',
 'Por favor, mencione las actividades asociadas a las prácticas de datos que se hayan desarrollado en la clase acompañada.',
 'Prácticas de Pensamiento Computacional - parte 2\n\n\n\n¿Se observan prácticas de programación?\n\nMarque sí si en la clase se invita a los/las estudiantes a dividir un problema en otros más pequeños, si se crean instrucciones paso a paso para resolver un problema, si se codifica (en bloques o en texto), o si se prueban y evalúan los resultados de una posible solución a fin de plantear mejoras.',
 'Programación\n\n\n\n\n¿Los/las estudiantes realizan actividades que implican descomponer los problemas en partes más pequeñas?',
 '¿Los/las estudiantes crean instrucciones paso a paso para resolver un problema?',
 '¿Los/las estudiantes utilizan un lenguaje de programación para codificar la solución a un problema?',
 '¿Los/las estudiantes ejecutan, depuran, y hacen ajustes o mejoras a sus programas?',
 'Por favor, mencione las actividades asociadas a programación que se hayan desarrollado en la clase acompañada.',
 'Prácticas de Pensamiento Computacional - parte 3\n\n\n¿Se observa el uso de simulaciones computacionales?\n\nMarque sí si en la clase se hace uso de aplicaciones interactivas para entender o probar fenómenos científicos o del mundo físico, o si se discuten las limitaciones que tienen una simulación en contraste con las condiciones del mundo real.',
 'Simulaciones\n\n¿Los/las estudiantes usan simuladores computacionales?',
 '¿La/El docente brinda espacios para que los/las estudiantes evalúen las simulaciones computacionales?\n\nEj. se les invita a considerar si hay otros factores que pudieran agregarse o modificarse para hacer una simulación más precisa que lo que permite la herramienta.',
 'Por favor, mencione las actividades asociadas a simulaciones computacionales que se hayan desarrollado en la clase acompañada.',
 'Prácticas de Pensamiento Computacional - parte 4\n\n\n\n¿Se observan prácticas asociadas al Pensamiento Sistémico?\n\nMarque sí si en la clase los/las estudiantes logran identificar las partes de un todo que son cuantificables, si logran identificar las relaciones numéricas entre diferentes partes de un sistema, o si logran identificar cómo el incremento de un factor tiene impacto en el incremento o decremento de otro elemento del sistema.',
 'Pensamiento sistémico\n\n\n¿La/El docente realiza actividades que permiten a los/las estudiantes identificar datos numéricos?\n\nEj. En una simulación sobre la cantidad de lluvia que cae en la ciudad, se invita a los/las estudiantes a considerar que las cifras se miden en milímetros cúbicos y corresponden a litros de agua por metro cuadrado',
 '¿Los/las estudiantes identifican las relaciones numéricas dentro de un sistema?\n\nEj. Los/las estudiantes analizan lo que sucede con los depredadores si se cambian los valores iniciales de las presas o del alimento disponible para estas, en una simulación presa-depredador.',
 '¿Los/las estudiantes analizan cómo los cambios en las variables contribuyen a los resultados del sistema?\n\nEj. Los estudiantes determinan qué pasa, repetición a repetición de una simulación, cuando se incrementa en 1 el número inicial de depredadores.',
 'Por favor, mencione las actividades asociadas a pensamiento sistémico que se hayan desarrollado en la clase acompañada.',
 'Ciudadanía digital y comprensión y uso de la IA\n\n\n¿Se observan prácticas que busquen fomentar habilidades de ciudadanía digital o promover la comprensión y el uso de la IA?\n\n\nMarque sí si en la clase los/las estudiantes aprenden conceptos básicos de Inteligencia Artificial  (IA, aprendizaje automático, modelo, algoritmo de aprendizaje, datos de entrenamiento, predicción, sesgos, etc.), realizan actividades desconectadas o conectadas de IA, o analizan problemas de seguridad, éticos y de sesgos asociados al uso de la tecnología con o sin IA.',
 'Ciudadanía digital y comprensión y uso de la IA\n\nResponda todas las preguntas y luego, si es posible, describa brevemente la actividad que se realizó durante la clase y que permitió evidenciar el acercamiento a la comprensión y uso de la Inteligencia Artificial por parte de los/las estudiantes.\n\n\n¿Los/las estudiantes llevan a cabo alguna actividad desconectada para fortalecer su comprensión de conceptos de IA?\n\nEjemplo: analizar aplicaciones u objetos y decidir si corresponden o no a ejemplos de IA, etiquetar imágenes y luego discutir sesgos en la interpretación de estas, determinar los datos de entrenamiento requeridos para alguna toma de decisión o predicción, etc).',
 '¿Los/las estudiantes usan herramientas de IA generativa?\nEjemplo: hacen una consulta a un modelo grande de lenguaje como ChatGPT, crean imágenes mediante un prompt en Copilot o Meta, generan un video con Canva, etc.',
 '¿Los/las estudiantes entrenan modelos de IA o hacen uso de uno de estos modelos?\nEjemplo: crean un modelo de reconocimiento de imágenes con TeachableMachine, crean un modelo de reconocimiento de texto con https://machinelearningforkids.co.uk/, vinculan un modelo de IA creado a un programa de Scratch o vinculan un proyecto en MakeCode con un modelo de IA usando https://makeairobots.com/, etc.',
 '¿Se realizan discusiones críticas sobre perspectiva, sesgos algorítmicos, o la necesidad de que población diversa contribuya en proyectos computacionales?\nEjemplo: se analizan las fallas de un modelo de IA para reconocer una imagen, se discute por qué un modelo de IA genera imágenes que representan un estereotipo, se comentan las ventajas de que varias personas distintas colaboren para entrenar un modelo de IA, etc',
 '¿Se discuten o promueven buenas prácticas de seguridad digital (ej. la protección de datos, contraseñas, y el uso seguro de internet)?',
 '¿Se abordan aspectos éticos del uso de tecnologías digitales (ej. respeto a la privacidad, uso responsable de la información)?',
 'Por favor, mencione las actividades asociadas a ciudadanía digital (seguridad informática, uso ético de tecnologías, equidad ) y/o de IA que se hayan desarrollado en la clase acompañada.',
 'Sobre los conocimientos técnicos del docente\n\n\n¿Se usa el vocabulario adecuado (terminología correcta) con relación al pensamiento computacional ?\n\nDiligencie esta parte durante la observación, y si es preciso, ajuste respuestas dadas previamente para responder mejor a la generalidad de lo observado',
 '¿Se conectan los temas presentados con la vida diaria?',
 '¿Sabe cómo resolver los problemas técnicos cuando fallan las herramientas computacionales en el aula?',
 'Si aplica, por favor, indique las dificultades técnicas que se presentaron durante la clase acompañada',
 'Sobre las prácticas pedagógicas y de gestión de aula\n\n\n\n¿Se preparó de forma previa el material requerido para la lección?',
 '¿Se gestionan correctamente los materiales e instrumentos para el desarrollo de las actividades propuestas?',
 '¿Se valora el esfuerzo de los estudiantes para desarrollar las actividades propuestas?',
 '¿Se observa acompañamiento con estrategias de apoyo (aclaración de dudas, explicaciones, ejemplos adicionales, invitación a revisar notas de clases previas, etc) a los estudiantes durante el desarrollo de las actividades?',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se corrigen comentarios y comportamientos sexistas',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se estimula el liderazgo femenino',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se realizan acciones afirmativas en términos de género',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se dedica tiempo de la clase a hacer reflexiones sobre equidad de género, por ejemplo, destacando los aportes de personajes masculinos y femeninos',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se hace uso de lenguaje inclusivo, sin estereotipos de género, que promueva respeto por la diversidad',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - No se observa ninguna práctica pedagógica en pro de la equidad de género',
 'Prácticas en pro de la equidad de género\n\n\nElija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Otra',
 'Otra',
 'Por favor, agregue cualquier otra información adicional que considere relevante para aclarar sus respuestas a la pregunta anterior',
 'Instantánea 1 - minuto 8 de la observación\n\n\n\n¿Qué está haciendo el/la docente ahora?\n\nIndique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.',
 'Indique con quiénes está interactuando el/la docente',
 '¿Con quiénes está interactuando el/la docente?',
 '¿Están los/las estudiantes respondiendo las preguntas y/o participando en las discusiones?',
 '¿Están los/las estudiantes escuchando atentamente al docente?',
 '¿Están los/las estudiantes tomando nota de las explicaciones o discusiones?',
 '¿Están los/las estudiantes haciendo preguntas y/o pidiendo ayuda al docente?',
 '¿Están los/las estudiantes socializando su trabajo?',
 '¿Quiénes están socializando su trabajo?',
 '¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?',
 '¿Quiénes no están involucrados en las actividades que lidera el/la docente?',
 '¿Están haciendo uso de herramientas computacionales?',
 '¿Quiénes están haciendo uso de herramientas computacionales?',
 '¿Están los/las estudiantes trabajando individualmente?',
 '¿Están los/las estudiantes trabajando en parejas o grupos?',
 '¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?',
 '¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?',
 'Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase',
 '¿Avanzar a la Instantánea 2?',
 'Timing - Primer clic.1',
 'Timing - Último clic.1',
 'Timing - Envío de página.1',
 'Timing - Recuento de clics.1',
 'Instantánea 2 - minuto 13 de la observación\n\n\n\n¿Qué está haciendo el/la docente ahora?\n\nIndique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.',
 'Indique con quiénes está interactuando el/la docente.1',
 '¿Con quiénes está interactuando el/la docente?.1',
 '¿Están los/las estudiantes respondiendo las preguntas y/o participando en las discusiones?.1',
 '¿Están los/las estudiantes escuchando atentamente al docente?.1',
 '¿Están los/las estudiantes tomando nota de las explicaciones o discusiones?.1',
 '¿Están los/las estudiantes haciendo preguntas y/o pidiendo ayuda al docente?.1',
 '¿Están los/las estudiantes socializando su trabajo?.1',
 '¿Quiénes están socializando su trabajo?.1',
 '¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?.1',
 '¿Quiénes no están involucrados en las actividades que lidera el/la docente?.1',
 '¿Están haciendo uso de herramientas computacionales?.1',
 '¿Quiénes están haciendo uso de herramientas computacionales?.1',
 '¿Están los/las estudiantes trabajando individualmente?.1',
 '¿Están los/las estudiantes trabajando en parejas o grupos?.1',
 '¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?.1',
 '¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?.1',

In [90]:
df['Mentor'] = df['Seleccione la institución educativa y docente a observar - Mentor']

In [91]:
df.filter(like='Mentor')

,Seleccione la institución educativa y docente a observar - Mentor,Mentor
0,Marcela Garcés Hoyos,Marcela Garcés Hoyos
1,Marcela Garcés Hoyos,Marcela Garcés Hoyos
2,Marcela Garcés Hoyos,Marcela Garcés Hoyos
3,Marcela Garcés Hoyos,Marcela Garcés Hoyos
4,Marcela Garcés Hoyos,Marcela Garcés Hoyos
5,Marcela Garcés Hoyos,Marcela Garcés Hoyos

In [92]:
def concatenate_columns(df, start_col, end_col, target_col):
    """
    Concatena los valores de las columnas desde start_col hasta end_col
    y los asigna a la columna target_col en cada fila.

    Args:
        df (pandas.DataFrame): DataFrame de entrada.
        start_col (str): Nombre de la primera columna a concatenar.
        end_col (str): Nombre de la última columna a concatenar.
        target_col (str): Nombre de la columna donde se guardará la concatenación.

    Returns:
        pandas.DataFrame: DataFrame con la columna target_col actualizada.
    """
    # Verifica que las columnas existan
    if start_col not in df.columns or end_col not in df.columns:
        raise ValueError("Alguna de las columnas especificadas no existe en el DataFrame.")

    # Obtiene los índices de las columnas
    start_idx = df.columns.get_loc(start_col)
    end_idx = df.columns.get_loc(end_col)

    # Selecciona las columnas a concatenar
    columns_to_concat = df.columns[start_idx:end_idx + 1]

    # Convierte los valores a string y concatena por fila, manejando NaN
    df[target_col] = df[columns_to_concat].astype(str).agg(' '.join, axis=1).str.replace('nan', '', regex=False)

    return df

# # Llamar a la función
# df = concatenate_columns(df, 'Mentor', 'Mentor.23', 'Mentor')
df["Mentor"]


# Función para limpiar espacios innecesarios en los valores de una columna
def clean_column_values(df, column_name):
    """
    Limpia los valores de una columna eliminando espacios al principio y al final,
    y reemplazando múltiples espacios consecutivos por un solo espacio.

    Args:
        df (pandas.DataFrame): DataFrame de entrada.
        column_name (str): Nombre de la columna cuyos valores se van a limpiar.

    Returns:
        pandas.DataFrame: DataFrame con la columna limpiada.
    """
    # Verifica que la columna exista
    if column_name not in df.columns:
        raise ValueError(f"La columna '{column_name}' no existe en el DataFrame.")

    # Aplica la limpieza a cada valor de la columna
    df[column_name] = df[column_name].apply(lambda x: re.sub(r'\s+', ' ', str(x).strip()) if pd.notnull(x) else x)

    return df

df = clean_column_values(df, 'Mentor')


def drop_column_range(df, start_col, end_col):
    """
    Elimina un rango de columnas consecutivas desde start_col hasta end_col (inclusive).

    Args:
        df (pandas.DataFrame): DataFrame de entrada.
        start_col (str): Nombre de la primera columna a eliminar.
        end_col (str): Nombre de la última columna a eliminar.

    Returns:
        pandas.DataFrame: DataFrame con las columnas eliminadas.
    """
    # Verifica que las columnas existan
    if start_col not in df.columns or end_col not in df.columns:
        raise ValueError("Alguna de las columnas especificadas no existe en el DataFrame.")

    # Obtiene los índices de las columnas
    start_idx = df.columns.get_loc(start_col)
    end_idx = df.columns.get_loc(end_col)

    # Crea una lista de columnas a eliminar usando slicing
    columns_to_drop = df.columns[start_idx:end_idx + 1].tolist()

    # Elimina las columnas
    df_dropped = df.drop(columns=columns_to_drop)

    return df_dropped

# df = drop_column_range(df, 'Mentor', 'Mentor.23')
# df = drop_column_range(df, 'UG1', 'UG24')
df = drop_column_range(df, 'Apellido del destinatario', 'Referencia a datos externos')

# Función para limpiar espacios innecesarios
def clean_column_name(col_name):
    # Eliminar espacios al principio y al final
    col_name = col_name.strip()
    # Reemplazar múltiples espacios consecutivos por un solo espacio
    col_name = re.sub(r'\s+', ' ', col_name)
    return col_name

# Aplicar la función de limpieza a los nombres de las columnas
df.columns = [clean_column_name(col) for col in df.columns]

In [93]:
copia = df.copy()

In [94]:
copia.columns.tolist()

['Fecha de inicio',
 'Fecha de finalización',
 'Tipo de respuesta',
 'Dirección IP',
 'Progreso',
 'Duración (en segundos)',
 'Finalizado',
 'Fecha registrada',
 'ID de respuesta',
 'Latitud de la ubicación',
 'Longitud de la ubicación',
 'Canal de la distribución',
 'Idioma del usuario',
 'Fecha del acompañamiento Indique la fecha en que realizó el acompañamiento en aula. Use el formato dd/mm/aaaa',
 'Hora de inicio de la clase (Formato Hora Militar) Indique la hora en la que inició la clase acompañada.',
 'Seleccione la institución educativa y docente a observar - Mentor',
 'Seleccione la institución educativa y docente a observar - Institución Educativa',
 'Seleccione la institución educativa y docente a observar - Nombre del/la docente observado',
 'Número de documento de docente observado',
 'Indique sexo del docente',
 'Asignatura - Selected Choice',
 'Asignatura - Otra - Texto',
 'Grado',
 '¿El/la docente trabaja con una guía pedagógica?',
 '¿A qué grado corresponde la guía pedagógica empleada?',
 '¿Con qué número de guía se trabaja?',
 '¿Con qué sesión de la guía se trabaja?',
 'Tema de la clase Si no se trabaja con una guía pedagógica, por favor indique el tema de la clase',
 'Número de estudiantes en total Número entero sin puntos',
 'Número de estudiantes de sexo femenino Número entero sin puntos',
 'Número de estudiantes de sexo masculino Número entero sin puntos',
 'Duración estimada de la clase (horas y minutos) Por favor escriba el tiempo estimado que debe durar la clase observada en formato horas y minutos (00:00). Por ejemplo, si la clase dura 50 minutos, debe colocar 00:50.',
 'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Computadores portátiles',
 'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Computadores de escritorio',
 'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Tabletas',
 'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Celulares',
 'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Tarjetas micro:bit',
 'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Video proyector (Video Beam)',
 'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - No se hizo uso de tecnologías digitales',
 'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Otra',
 'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Otra - Texto',
 'Timing - Primer clic',
 'Timing - Último clic',
 'Timing - Envío de página',
 'Timing - Recuento de clics',
 'Al inicio de la clase ¿Cuántos minutos transcurren entre la hora de inicio y el momento en que el docente empieza a gestionar el aula para empezar la clase? Escriba la cantidad de minutos en números enteros. Nota: Las actividades gestión inicial como llamar a lista o seguir rutinas de inicio establecidas, se consideran parte de la clase.',
 '¿Se presentan los objetivos de aprendizaje de la lección?',
 '¿Se exploran los conocimientos previos de los estudiantes y su conexión con los temas de la lección?',
 '¿Se presentan claramente los conceptos claves que serán usados en la lección?',
 'Actividades que promueven subhabilidades del pensamiento computacional ¿Se realizan actividades que promueven el uso de abstracción, descomposición, pensamiento lógico, pensamiento algorítmico, depuración o reconocimiento de patrones por parte de los/las estudiantes? Marque sí, si en la clase se realiza alguna actividad práctica de la asignatura que busque promover alguna de las 6 subhabilidades del pensamiento computacional. Ej. En clase de matemáticas se pide a los a los/las estudiantes que sigan una secuencia de pasos específica para realizar una tarea (algoritmia) o que analicen la solución de un ejercicio a fin de encontrar algún error que se haya cometido durante el proceso (depuración).',
 'Fomento de las subhabilidades del pensamiento computacional Responda todas las preguntas y luego, si es posible, describa brevemente la actividad que se realizó en el aula y que permitió promover el uso de las subhabilidades de pensamiento computacional. Descomposición: ¿Durante la clase se realizan actividades que requieren descomponer un problema o proceso en partes más pequeñas? Ej. Se pide a los estudiantes que planteen las actividades generales que desarrollarán en cada etapa del método científico, antes de proponer y ejecutar un experimento.',
 'Reconocimiento de patrones: ¿Los/las estudiantes realizan actividades para encontrar patrones y relaciones entre elementos? Ej. Se pide a los/las estudiantes analizar las células animal y vegeta y luego crear un listado de las características comunes y las diferencias entre ellas.',
 'Pensamiento algorítmico: ¿La/El docente invita a los/las estudiantes a organizar y/o ejecutar una secuencia de pasos para llevar a cabo una tarea? Ej. Se entrega a los/las estudiantes un laboratorio de física que requiere el desarrollo secuencial de ciertas actividades y se monitorea el avance.',
 'Depuración: ¿La/El docente solicita a los/las estudiantes identificar y corregir errores en la ejecución de un proceso o tarea? Ej. Se pide a los/las estudiantes intercambiar sus respuestas a un taller, marcar las fallas detectadas en el trabajo de sus compañeros y darles una recomendación escrita sobre lo que deben hacer para corregirlas.',
 'Abstracción: ¿Se solicita a las/los estudiantes identificar la información relevante sobre un tema y/o sintetizarla? Ej. Se presenta un problema situacional matemático y se pide a los/las estudiantes leer atentamente el enunciado y plantear la ecuación para solucionarlo.',
 'Pensamiento lógico: ¿Se requiere que las/los estudiantes evalúen si se cumplen o no algunas condiciones y/o que realicen tareas o tomen decisiones a partir de los resultados de esta evaluación? Ej. Se presenta a los estudiantes un listado de hábitos diarios para que los analicen y determinen cuáles de ellos podrían afectar positiva o negativamente al sistema excretor.',
 'Por favor, mencione las actividades que se realizaron en la clase acompañada, que a su juicio, contribuyen al desarrollo de una o más subhabilidades del pensamiento computacional de los/las estudiantes.',
 'Prácticas de Pensamiento Computacional - parte 1 ¿Se observan prácticas de datos? Marque sí si en la clase se recopilan datos mediante generan o recolectan datos haciendo uso de herramientas computacionales, organización y clasificación de datos, análisis de los patrones existentes en los datos, o si se generan tablas o gráficos a partir de datos.',
 'Prácticas de Datos ¿Durante la clase se realizan actividades para recolectar datos con herramientas tecnológicas? Ej. Se utiliza la micro:bit para recolectar datos de temperatura o se ingresan registros de observaciones en una hoja de cálculo para hacerles posterior análisis.',
 '¿Los/las estudiantes realizan actividades para encontrar patrones y relaciones en conjuntos de datos? Ej. hacen conteo de frecuencias y las comparan, o hacen análisis de medias y tendencias.',
 '¿La/El docente invita a los/las estudiantes a organizar y clasificar datos? Ej. Se pide a los/las estudiantes organizar los registros de observaciones de mayor a menor para identificar valores máximos y mínimos.',
 '¿La/El docente propone realizar tablas, graficas o diagramas con los datos? Ej. Se pide a los/las estudiantes hacer una gráfica de barras o crear un gráfico estadístico utilizando herramientas de una hoja de cálculo o de forma desconectada',
 'Por favor, mencione las actividades asociadas a las prácticas de datos que se hayan desarrollado en la clase acompañada.',
 'Prácticas de Pensamiento Computacional - parte 2 ¿Se observan prácticas de programación? Marque sí si en la clase se invita a los/las estudiantes a dividir un problema en otros más pequeños, si se crean instrucciones paso a paso para resolver un problema, si se codifica (en bloques o en texto), o si se prueban y evalúan los resultados de una posible solución a fin de plantear mejoras.',
 'Programación ¿Los/las estudiantes realizan actividades que implican descomponer los problemas en partes más pequeñas?',
 '¿Los/las estudiantes crean instrucciones paso a paso para resolver un problema?',
 '¿Los/las estudiantes utilizan un lenguaje de programación para codificar la solución a un problema?',
 '¿Los/las estudiantes ejecutan, depuran, y hacen ajustes o mejoras a sus programas?',
 'Por favor, mencione las actividades asociadas a programación que se hayan desarrollado en la clase acompañada.',
 'Prácticas de Pensamiento Computacional - parte 3 ¿Se observa el uso de simulaciones computacionales? Marque sí si en la clase se hace uso de aplicaciones interactivas para entender o probar fenómenos científicos o del mundo físico, o si se discuten las limitaciones que tienen una simulación en contraste con las condiciones del mundo real.',
 'Simulaciones ¿Los/las estudiantes usan simuladores computacionales?',
 '¿La/El docente brinda espacios para que los/las estudiantes evalúen las simulaciones computacionales? Ej. se les invita a considerar si hay otros factores que pudieran agregarse o modificarse para hacer una simulación más precisa que lo que permite la herramienta.',
 'Por favor, mencione las actividades asociadas a simulaciones computacionales que se hayan desarrollado en la clase acompañada.',
 'Prácticas de Pensamiento Computacional - parte 4 ¿Se observan prácticas asociadas al Pensamiento Sistémico? Marque sí si en la clase los/las estudiantes logran identificar las partes de un todo que son cuantificables, si logran identificar las relaciones numéricas entre diferentes partes de un sistema, o si logran identificar cómo el incremento de un factor tiene impacto en el incremento o decremento de otro elemento del sistema.',
 'Pensamiento sistémico ¿La/El docente realiza actividades que permiten a los/las estudiantes identificar datos numéricos? Ej. En una simulación sobre la cantidad de lluvia que cae en la ciudad, se invita a los/las estudiantes a considerar que las cifras se miden en milímetros cúbicos y corresponden a litros de agua por metro cuadrado',
 '¿Los/las estudiantes identifican las relaciones numéricas dentro de un sistema? Ej. Los/las estudiantes analizan lo que sucede con los depredadores si se cambian los valores iniciales de las presas o del alimento disponible para estas, en una simulación presa-depredador.',
 '¿Los/las estudiantes analizan cómo los cambios en las variables contribuyen a los resultados del sistema? Ej. Los estudiantes determinan qué pasa, repetición a repetición de una simulación, cuando se incrementa en 1 el número inicial de depredadores.',
 'Por favor, mencione las actividades asociadas a pensamiento sistémico que se hayan desarrollado en la clase acompañada.',
 'Ciudadanía digital y comprensión y uso de la IA ¿Se observan prácticas que busquen fomentar habilidades de ciudadanía digital o promover la comprensión y el uso de la IA? Marque sí si en la clase los/las estudiantes aprenden conceptos básicos de Inteligencia Artificial (IA, aprendizaje automático, modelo, algoritmo de aprendizaje, datos de entrenamiento, predicción, sesgos, etc.), realizan actividades desconectadas o conectadas de IA, o analizan problemas de seguridad, éticos y de sesgos asociados al uso de la tecnología con o sin IA.',
 'Ciudadanía digital y comprensión y uso de la IA Responda todas las preguntas y luego, si es posible, describa brevemente la actividad que se realizó durante la clase y que permitió evidenciar el acercamiento a la comprensión y uso de la Inteligencia Artificial por parte de los/las estudiantes. ¿Los/las estudiantes llevan a cabo alguna actividad desconectada para fortalecer su comprensión de conceptos de IA? Ejemplo: analizar aplicaciones u objetos y decidir si corresponden o no a ejemplos de IA, etiquetar imágenes y luego discutir sesgos en la interpretación de estas, determinar los datos de entrenamiento requeridos para alguna toma de decisión o predicción, etc).',
 '¿Los/las estudiantes usan herramientas de IA generativa? Ejemplo: hacen una consulta a un modelo grande de lenguaje como ChatGPT, crean imágenes mediante un prompt en Copilot o Meta, generan un video con Canva, etc.',
 '¿Los/las estudiantes entrenan modelos de IA o hacen uso de uno de estos modelos? Ejemplo: crean un modelo de reconocimiento de imágenes con TeachableMachine, crean un modelo de reconocimiento de texto con https://machinelearningforkids.co.uk/, vinculan un modelo de IA creado a un programa de Scratch o vinculan un proyecto en MakeCode con un modelo de IA usando https://makeairobots.com/, etc.',
 '¿Se realizan discusiones críticas sobre perspectiva, sesgos algorítmicos, o la necesidad de que población diversa contribuya en proyectos computacionales? Ejemplo: se analizan las fallas de un modelo de IA para reconocer una imagen, se discute por qué un modelo de IA genera imágenes que representan un estereotipo, se comentan las ventajas de que varias personas distintas colaboren para entrenar un modelo de IA, etc',
 '¿Se discuten o promueven buenas prácticas de seguridad digital (ej. la protección de datos, contraseñas, y el uso seguro de internet)?',
 '¿Se abordan aspectos éticos del uso de tecnologías digitales (ej. respeto a la privacidad, uso responsable de la información)?',
 'Por favor, mencione las actividades asociadas a ciudadanía digital (seguridad informática, uso ético de tecnologías, equidad ) y/o de IA que se hayan desarrollado en la clase acompañada.',
 'Sobre los conocimientos técnicos del docente ¿Se usa el vocabulario adecuado (terminología correcta) con relación al pensamiento computacional ? Diligencie esta parte durante la observación, y si es preciso, ajuste respuestas dadas previamente para responder mejor a la generalidad de lo observado',
 '¿Se conectan los temas presentados con la vida diaria?',
 '¿Sabe cómo resolver los problemas técnicos cuando fallan las herramientas computacionales en el aula?',
 'Si aplica, por favor, indique las dificultades técnicas que se presentaron durante la clase acompañada',
 'Sobre las prácticas pedagógicas y de gestión de aula ¿Se preparó de forma previa el material requerido para la lección?',
 '¿Se gestionan correctamente los materiales e instrumentos para el desarrollo de las actividades propuestas?',
 '¿Se valora el esfuerzo de los estudiantes para desarrollar las actividades propuestas?',
 '¿Se observa acompañamiento con estrategias de apoyo (aclaración de dudas, explicaciones, ejemplos adicionales, invitación a revisar notas de clases previas, etc) a los estudiantes durante el desarrollo de las actividades?',
 'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se corrigen comentarios y comportamientos sexistas',
 'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se estimula el liderazgo femenino',
 'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se realizan acciones afirmativas en términos de género',
 'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se dedica tiempo de la clase a hacer reflexiones sobre equidad de género, por ejemplo, destacando los aportes de personajes masculinos y femeninos',
 'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se hace uso de lenguaje inclusivo, sin estereotipos de género, que promueva respeto por la diversidad',
 'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - No se observa ninguna práctica pedagógica en pro de la equidad de género',
 'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Otra',
 'Otra',
 'Por favor, agregue cualquier otra información adicional que considere relevante para aclarar sus respuestas a la pregunta anterior',
 'Instantánea 1 - minuto 8 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.',
 'Indique con quiénes está interactuando el/la docente',
 '¿Con quiénes está interactuando el/la docente?',
 '¿Están los/las estudiantes respondiendo las preguntas y/o participando en las discusiones?',
 '¿Están los/las estudiantes escuchando atentamente al docente?',
 '¿Están los/las estudiantes tomando nota de las explicaciones o discusiones?',
 '¿Están los/las estudiantes haciendo preguntas y/o pidiendo ayuda al docente?',
 '¿Están los/las estudiantes socializando su trabajo?',
 '¿Quiénes están socializando su trabajo?',
 '¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?',
 '¿Quiénes no están involucrados en las actividades que lidera el/la docente?',
 '¿Están haciendo uso de herramientas computacionales?',
 '¿Quiénes están haciendo uso de herramientas computacionales?',
 '¿Están los/las estudiantes trabajando individualmente?',
 '¿Están los/las estudiantes trabajando en parejas o grupos?',
 '¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?',
 '¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?',
 'Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase',
 '¿Avanzar a la Instantánea 2?',
 'Timing - Primer clic.1',
 'Timing - Último clic.1',
 'Timing - Envío de página.1',
 'Timing - Recuento de clics.1',
 'Instantánea 2 - minuto 13 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.',
 'Indique con quiénes está interactuando el/la docente.1',
 '¿Con quiénes está interactuando el/la docente?.1',
 '¿Están los/las estudiantes respondiendo las preguntas y/o participando en las discusiones?.1',
 '¿Están los/las estudiantes escuchando atentamente al docente?.1',
 '¿Están los/las estudiantes tomando nota de las explicaciones o discusiones?.1',
 '¿Están los/las estudiantes haciendo preguntas y/o pidiendo ayuda al docente?.1',
 '¿Están los/las estudiantes socializando su trabajo?.1',
 '¿Quiénes están socializando su trabajo?.1',
 '¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?.1',
 '¿Quiénes no están involucrados en las actividades que lidera el/la docente?.1',
 '¿Están haciendo uso de herramientas computacionales?.1',
 '¿Quiénes están haciendo uso de herramientas computacionales?.1',
 '¿Están los/las estudiantes trabajando individualmente?.1',
 '¿Están los/las estudiantes trabajando en parejas o grupos?.1',
 '¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?.1',
 '¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?.1',
 'Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase.1',
 '¿Avanzar a la Instantánea 3?',
 'Timing - Primer clic.2',
 'Timing - Último clic.2',
 'Timing - Envío de página.2',
 'Timing - Recuento de clics.2',

In [95]:
# Nombre actual de la columna
nombre_actual = 'Número de documento de docente observado/a'

# Nuevo nombre deseado
nuevo_nombre = 'Número de documento de docente observado'
df = df.rename(columns={nombre_actual: nuevo_nombre})

In [96]:
lista_instantaneas= ["Instantánea 1 - minuto 8 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 2 - minuto 13 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 3 - minuto 18 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 4 - minuto 23 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 5 - minuto 28 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 6 - minuto 33 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 7 - minuto 38 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 8 - minuto 43 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 9 - minuto 48 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 10 - minuto 53 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 11 - minuto 58 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.","Instantánea 12 - minuto 63 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante."]

columnas = [
    "¿Qué está haciendo el/la docente ahora?",
    "Indique con quiénes está interactuando el/la docente",
    "¿Con quiénes está interactuando el/la docente?",
    "¿Están los/las estudiantes respondiendo las preguntas y/o participando en las discusiones?",
    "¿Están los/las estudiantes escuchando atentamente al docente?",
    "¿Están los/las estudiantes tomando nota de las explicaciones o discusiones?",
    "¿Están los/las estudiantes haciendo preguntas y/o pidiendo ayuda al docente?",
    "¿Están los/las estudiantes socializando su trabajo?",
    "¿Quiénes están socializando su trabajo?",
    "¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?",
    "¿Quiénes no están involucrados en las actividades que lidera el/la docente?",
    "¿Están haciendo uso de herramientas computacionales?",
    "¿Quiénes están haciendo uso de herramientas computacionales?",
    "¿Están los/las estudiantes trabajando individualmente?",
    "¿Están los/las estudiantes trabajando en parejas o grupos?",
    "¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?",
    "¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?",
    "Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase",
    'ID de respuesta',
    "Número de documento de docente observado",
    "Indique sexo del docente",
    "¿El/la docente trabaja con una guía pedagógica?",
    "Asignatura - Selected Choice",
    "Visita",
    "Momento",
    "Número de instantánea",  # Nueva primera columna,
]
instantaneas = pd.DataFrame()

i = 1
for instantanea in lista_instantaneas:
  print(instantanea)
  columna = df.columns.get_loc(instantanea)

  tablita = df.iloc[:,columna:columna+18]
  tablita = tablita.rename(columns={instantanea:'¿Qué está haciendo el/la docente ahora?' })
  tablita = tablita.merge(df.loc[:,['ID de respuesta',"Número de documento de docente observado",'Indique sexo del docente', '¿El/la docente trabaja con una guía pedagógica?','Asignatura - Selected Choice',"Visita", "Momento"]], left_index=True, right_index=True)
  tablita.loc[:,'Número de instantánea'] = i
  tablita.columns = columnas
  instantaneas = pd.concat([instantaneas,tablita],axis=0)
  i=i+1

Instantánea 1 - minuto 8 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 2 - minuto 13 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 3 - minuto 18 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 4 - minuto 23 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 5 - minuto 28 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 6 - minuto 33 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 7 - minuto 38 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 8 - minuto 43 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 9 - minuto 48 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 10 - minuto 53 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 11 - minuto 58 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.
Instantánea 12 - minuto 63 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.

In [97]:
nuevo_orden = ['ID de respuesta',
 'Número de instantánea', 'Momento', 'Visita',
 'Número de documento de docente observado',
 'Indique sexo del docente',
 '¿El/la docente trabaja con una guía pedagógica?',
 'Asignatura - Selected Choice',
 'Codigo','¿Qué está haciendo el/la docente ahora?',
 'Indique con quiénes está interactuando el/la docente',
 '¿Con quiénes está interactuando el/la docente?',
 '¿Están los/las estudiantes respondiendo las preguntas y/o participando en las discusiones?',
 '¿Están los/las estudiantes escuchando atentamente al docente?',
 '¿Están los/las estudiantes tomando nota de las explicaciones o discusiones?',
 '¿Están los/las estudiantes haciendo preguntas y/o pidiendo ayuda al docente?',
 '¿Están los/las estudiantes socializando su trabajo?',
 '¿Quiénes están socializando su trabajo?',
 '¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?',
 '¿Quiénes no están involucrados en las actividades que lidera el/la docente?',
 '¿Están haciendo uso de herramientas computacionales?',
 '¿Quiénes están haciendo uso de herramientas computacionales?',
 '¿Están los/las estudiantes trabajando individualmente?',
 '¿Están los/las estudiantes trabajando en parejas o grupos?',
 '¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?',
 '¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?',
 'Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase']
instantaneas = instantaneas.reindex(columns=nuevo_orden)

In [98]:
instantaneas

,ID de respuesta,Número de instantánea,Momento,Visita,Número de documento de docente observado,Indique sexo del docente,¿El/la docente trabaja con una guía pedagógica?,Asignatura - Selected Choice,Codigo,¿Qué está haciendo el/la docente ahora?,...,¿Quiénes están socializando su trabajo?,"¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?",¿Quiénes no están involucrados en las actividades que lidera el/la docente?,¿Están haciendo uso de herramientas computacionales?,¿Quiénes están haciendo uso de herramientas computacionales?,¿Están los/las estudiantes trabajando individualmente?,¿Están los/las estudiantes trabajando en parejas o grupos?,¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?,"¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?","Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase"
0,R_5iF6jTr3hvUIYHT,1,Post,2,1.028796e+07,Hombre,Sí,Física,NaN,Está dando una explicación temática,...,NaN,Ninguno,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,En este momento se encuentra el docente presen...
1,R_7Oe7ZAcrnQzWtoh,1,Post,2,2.443666e+07,Mujer,No,Matemáticas,NaN,Está haciendo actividades de gestión de aula (...,...,NaN,La mayoría,Niños y niñas por igual,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,La docente se encuetnra llamando la atención a...
2,R_31dqVm3EeEdIJqi,1,Post,2,3.073847e+07,Mujer,No,Matemáticas,NaN,Está haciendo preguntas a los/las estudiantes,...,NaN,Ninguno,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,La docente esta conectgando el nuevo conocimin...
3,R_310nLwVtnbAjLFy,1,Post,2,7.506251e+07,Hombre,No,Matemáticas,NaN,Está dando una explicación temática,...,NaN,Ninguno,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,En este omento el docente se encuentra present...
4,R_7X70SCcie932mQx,1,Post,2,1.053781e+09,Hombre,No,Física,NaN,Está dando una explicación temática,...,NaN,Ninguno,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,El docente se encuentra presentando el objetiv...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,R_7Oe7ZAcrnQzWtoh,12,Post,2,2.443666e+07,Mujer,No,Matemáticas,NaN,Está haciendo preguntas a los/las estudiantes,...,NaN,Ninguno,NaN,Ninguno,NaN,Ninguno,Todos(as),Niños y niñas por igual,Ninguno,La docente esa lanzando la pregunta a los estu...
2,R_31dqVm3EeEdIJqi,12,Post,2,3.073847e+07,Mujer,No,Matemáticas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,R_310nLwVtnbAjLFy,12,Post,2,7.506251e+07,Hombre,No,Matemáticas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,R_7X70SCcie932mQx,12,Post,2,1.053781e+09,Hombre,No,Física,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,R_1EWNOwR7k9SdwrL,12,Post,2,1.053818e+09,Hombre,No,Física,NaN,Está escuchando las intervenciones o presentac...,...,Niños y niñas por igual,Ninguno,NaN,Ninguno,NaN,Ninguno,Todos(as),No se evidencian roles de liderazgo,Ninguno,Un representante de cada grupo se encuetnra so...

In [99]:
rename_dict = {
    'Fecha de inicio': 'fecha_inicio',
    'Fecha de finalización': 'fecha_fin',
    'Momento': 'momento',
    'Visita': 'visita',
    'Tipo de respuesta': 'tipo_respuesta',
    'Dirección IP': 'ip',
    'Progreso': 'progreso',
    'Duración (en segundos)': 'duracion_seg',
    'Finalizado': 'finalizado',
    'Fecha registrada': 'fecha_registro',
    'ID de respuesta': 'id_respuesta',
    'Latitud de la ubicación': 'latitud',
    'Longitud de la ubicación': 'longitud',
    'Canal de la distribución': 'canal_dist',
    'Idioma del usuario': 'idioma',
    'Fecha del acompañamiento Indique la fecha en que realizó el acompañamiento en aula. Use el formato dd/mm/aaaa': 'fecha_acomp',
    'Hora de inicio de la clase (Formato Hora Militar) Indique la hora en la que inició la clase acompañada.': 'hora_inicio',
    'Unidad': 'unidad',
    'Mentor': 'mentor',
    'UG1': 'ug_1',
    'Número de documento de docente observado': 'doc_docente',
    'Nombre de docente observado/a': 'nombre_docente',
    'Indique sexo del docente': 'sexo_docente',
    'Asignatura - Selected Choice': 'asignatura',
    'Otra': 'otra_asignatura',
    'Grado': 'grado',
    '¿El/la docente trabaja con una guía pedagógica?': 'guia_pedagogica',
    '¿A qué grado corresponde la guía pedagógica empleada?': 'grado_guia',
    '¿Con qué número de guía se trabaja?': 'num_guia',
    '¿Con qué sesión de la guía se trabaja?': 'sesion_guia',
    'Tema de la clase Si no se trabaja con una guía pedagógica, por favor indique el tema de la clase': 'tema_clase',
    'Número de estudiantes en total Número entero sin puntos': 'total_estudiantes',
    'Número de estudiantes de sexo femenino Número entero sin puntos': 'est_femenino',
    'Número de estudiantes de sexo masculino Número entero sin puntos': 'est_masculino',
    'Duración estimada de la clase (horas y minutos) Por favor escriba el tiempo estimado que debe durar la clase observada en formato horas y minutos (00:00). Por ejemplo, si la clase dura 50 minutos, debe colocar 00:50.': 'duracion_clase',
    'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Computadores portátiles': 'tech_portatiles',
    'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Computadores de escritorio': 'tech_escritorio',
    'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Tabletas': 'tech_tabletas',
    'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Celulares': 'tech_celulares',
    'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Tarjetas micro:bit': 'tech_microbit',
    'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Video proyector (Video Beam)': 'tech_proyector',
    'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - No se hizo uso de tecnologías digitales': 'tech_ninguna',
    'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Selected Choice - Otra': 'tech_otra',
    'Tecnologías digitales disponibles en la clase Elija todas las que apliquen - Otra - Texto': 'tech_otra_detalle',
    'Timing - Primer clic': 'click_inicio',
    '¿Se promueven los procesos de metacognición y reflexión?': 'metacognicion',
    'Timing - Último clic': 'click_fin',
    'Timing - Envío de página': 'envio_pagina',
    'Timing - Recuento de clics': 'num_clics',
    'Al cierre de la clase ¿Se hace uso de algún tipo de gráfico de anclaje o memoria colectiva?': 'uso_grafico_anclaje',
    'Al inicio de la clase ¿Cuántos minutos transcurren entre la hora de inicio y el momento en que el docente empieza a gestionar el aula para empezar la clase? Escriba la cantidad de minutos en números enteros. Nota: Las actividades gestión inicial como llamar a lista o seguir rutinas de inicio establecidas, se consideran parte de la clase.': 'min_inicio_gestion',
    '¿Se presentan los objetivos de aprendizaje de la lección?': 'objetivos_aprend',
    '¿Se exploran los conocimientos previos de los estudiantes y su conexión con los temas de la lección?': 'conoc_previos',
    '¿Se presentan claramente los conceptos claves que serán usados en la lección?': 'conceptos_clave',
    'Actividades que promueven subhabilidades del pensamiento computacional ¿Se realizan actividades que promueven el uso de abstracción, descomposición, pensamiento lógico, pensamiento algorítmico, depuración o reconocimiento de patrones por parte de los/las estudiantes? Marque sí, si en la clase se realiza alguna actividad práctica de la asignatura que busque promover alguna de las 6 subhabilidades del pensamiento computacional. Ej. En clase de matemáticas se pide a los a los/las estudiantes que sigan una secuencia de pasos específica para realizar una tarea (algoritmia) o que analicen la solución de un ejercicio a fin de encontrar algún error que se haya cometido durante el proceso (depuración).': 'subhabilidades_comp',
    'Fomento de las subhabilidades del pensamiento computacional Responda todas las preguntas y luego, si es posible, describa brevemente la actividad que se realizó en el aula y que permitió promover el uso de las subhabilidades de pensamiento computacional. Descomposición: ¿Durante la clase se realizan actividades que requieren descomponer un problema o proceso en partes más pequeñas? Ej. Se pide a los estudiantes que planteen las actividades generales que desarrollarán en cada etapa del método científico, antes de proponer y ejecutar un experimento.': 'descomposicion',
    'Reconocimiento de patrones: ¿Los/las estudiantes realizan actividades para encontrar patrones y relaciones entre elementos? Ej. Se pide a los/las estudiantes analizar las células animal y vegeta y luego crear un listado de las características comunes y las diferencias entre ellas.': 'patrones',
    'Pensamiento algorítmico: ¿La/El docente invita a los/las estudiantes a organizar y/o ejecutar una secuencia de pasos para llevar a cabo una tarea? Ej. Se entrega a los/las estudiantes un laboratorio de física que requiere el desarrollo secuencial de ciertas actividades y se monitorea el avance.': 'algoritmico',
    'Depuración: ¿La/El docente solicita a los/las estudiantes identificar y corregir errores en la ejecución de un proceso o tarea? Ej. Se pide a los/las estudiantes intercambiar sus respuestas a un taller, marcar las fallas detectadas en el trabajo de sus compañeros y darles una recomendación escrita sobre lo que deben hacer para corregirlas.': 'depuracion',
    'Abstracción: ¿Se solicita a las/los estudiantes identificar la información relevante sobre un tema y/o sintetizarla? Ej. Se presenta un problema situacional matemático y se pide a los/las estudiantes leer atentamente el enunciado y plantear la ecuación para solucionarlo.': 'abstraccion',
    'Pensamiento lógico: ¿Se requiere que las/los estudiantes evalúen si se cumplen o no algunas condiciones y/o que realicen tareas o tomen decisiones a partir de los resultados de esta evaluación? Ej. Se presenta a los estudiantes un listado de hábitos diarios para que los analicen y determinen cuáles de ellos podrían afectar positiva o negativamente al sistema excretor.': 'logico',
    'Por favor, mencione las actividades que se realizaron en la clase acompañada, que a su juicio, contribuyen al desarrollo de una o más subhabilidades del pensamiento computacional de los/las estudiantes.': 'actividades_comp',
    'Prácticas de Pensamiento Computacional - parte 1 ¿Se observan prácticas de datos? Marque sí si en la clase se recopilan datos mediante generan o recolectan datos haciendo uso de herramientas computacionales, organización y clasificación de datos, análisis de los patrones existentes en los datos, o si se generan tablas o gráficos a partir de datos.': 'practicas_datos',
    'Prácticas de Datos ¿Durante la clase se realizan actividades para recolectar datos con herramientas tecnológicas? Ej. Se utiliza la micro:bit para recolectar datos de temperatura o se ingresan registros de observaciones en una hoja de cálculo para hacerles posterior análisis.': 'recoleccion_datos',
    '¿Los/las estudiantes realizan actividades para encontrar patrones y relaciones en conjuntos de datos? Ej. hacen conteo de frecuencias y las comparan, o hacen análisis de medias y tendencias.': 'patrones_datos',
    '¿La/El docente invita a los/las estudiantes a organizar y clasificar datos? Ej. Se pide a los/las estudiantes organizar los registros de observaciones de mayor a menor para identificar valores máximos y mínimos.': 'organizacion_datos',
    '¿La/El docente propone realizar tablas, graficas o diagramas con los datos? Ej. Se pide a los/las estudiantes hacer una gráfica de barras o crear un gráfico estadístico utilizando herramientas de una hoja de cálculo o de forma desconectada': 'visualizacion_datos',
    'Por favor, mencione las actividades asociadas a las prácticas de datos que se hayan desarrollado en la clase acompañada.': 'actividades_datos',
    'Prácticas de Pensamiento Computacional - parte 2 ¿Se observan prácticas de programación? Marque sí si en la clase se invita a los/las estudiantes a dividir un problema en otros más pequeños, si se crean instrucciones paso a paso para resolver un problema, si se codifica (en bloques o en texto), o si se prueban y evalúan los resultados de una posible solución a fin de plantear mejoras.': 'practicas_programacion',
    'Programación ¿Los/las estudiantes realizan actividades que implican descomponer los problemas en partes más pequeñas?': 'descomposicion_prog',
    '¿Los/las estudiantes crean instrucciones paso a paso para resolver un problema?': 'instrucciones_prog',
    '¿Los/las estudiantes utilizan un lenguaje de programación para codificar la solución a un problema?': 'codificacion',
    '¿Los/las estudiantes ejecutan, depuran, y hacen ajustes o mejoras a sus programas?': 'depuracion_prog',
    'Por favor, mencione las actividades asociadas a programación que se hayan desarrollado en la clase acompañada.': 'actividades_programacion',
    'Prácticas de Pensamiento Computacional - parte 3 ¿Se observa el uso de simulaciones computacionales? Marque sí si en la clase se hace uso de aplicaciones interactivas para entender o probar fenómenos científicos o del mundo físico, o si se discuten las limitaciones que tienen una simulación en contraste con las condiciones del mundo real.': 'simulaciones',
    'Simulaciones ¿Los/las estudiantes usan simuladores computacionales?': 'uso_simuladores',
    '¿La/El docente brinda espacios para que los/las estudiantes evalúen las simulaciones computacionales? Ej. se les invita a considerar si hay otros factores que pudieran agregarse o modificarse para hacer una simulación más precisa que lo que permite la herramienta.': 'evaluacion_simulaciones',
    'Por favor, mencione las actividades asociadas a simulaciones computacionales que se hayan desarrollado en la clase acompañada.': 'actividades_simulaciones',
    'Prácticas de Pensamiento Computacional - parte 4 ¿Se observan prácticas asociadas al Pensamiento Sistémico? Marque sí si en la clase los/las estudiantes logran identificar las partes de un todo que son cuantificables, si logran identificar las relaciones numéricas entre diferentes partes de un sistema, o si logran identificar cómo el incremento de un factor tiene impacto en el incremento o decremento de otro elemento del sistema.': 'pensamiento_sistemico',
    'Pensamiento sistémico ¿La/El docente realiza actividades que permiten a los/las estudiantes identificar datos numéricos? Ej. En una simulación sobre la cantidad de lluvia que cae en la ciudad, se invita a los/las estudiantes a considerar que las cifras se miden en milímetros cúbicos y corresponden a litros de agua por metro cuadrado': 'datos_numericos',
    '¿Los/las estudiantes identifican las relaciones numéricas dentro de un sistema? Ej. Los/las estudiantes analizan lo que sucede con los depredadores si se cambian los valores iniciales de las presas o del alimento disponible para estas, en una simulación presa-depredador.': 'relaciones_numericas',
    '¿Los/las estudiantes analizan cómo los cambios en las variables contribuyen a los resultados del sistema? Ej. Los estudiantes determinan qué pasa, repetición a repetición de una simulación, cuando se incrementa en 1 el número inicial de depredadores.': 'impacto_variables',
    'Por favor, mencione las actividades asociadas a pensamiento sistémico que se hayan desarrollado en la clase acompañada.': 'actividades_sistemico',
    'Sobre los conocimientos técnicos del docente ¿Se usa el vocabulario adecuado (terminología correcta) con relación al pensamiento computacional ? Diligencie esta parte durante la observación, y si es preciso, ajuste respuestas dadas previamente para responder mejor a la generalidad de lo observado': 'vocabulario_comp',
    '¿Se conectan los temas presentados con la vida diaria?': 'conexion_vida',
    '¿Sabe cómo resolver los problemas técnicos cuando fallan las herramientas computacionales en el aula?': 'resolucion_tecnica',
    'Si aplica, por favor, indique las dificultades técnicas que se presentaron durante la clase acompañada': 'dificultades_tecnicas',
    'Sobre las prácticas pedagógicas y de gestión de aula ¿Se preparó de forma previa el material requerido para la lección?': 'prep_material',
    '¿Se gestionan correctamente los materiales e instrumentos para el desarrollo de las actividades propuestas?': 'gestion_material',
    '¿Se valora el esfuerzo de los estudiantes para desarrollar las actividades propuestas?': 'valoracion_esfuerzo',
    '¿Se observa acompañamiento con estrategias de apoyo (aclaración de dudas, explicaciones, ejemplos adicionales, invitación a revisar notas de clases previas, etc) a los estudiantes durante el desarrollo de las actividades?': 'apoyo_estudiantes',
    'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se corrigen comentarios y comportamientos sexistas': 'equidad_corrige_sexismo',
    'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se estimula el liderazgo femenino': 'equidad_liderazgo_fem',
    'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se realizan acciones afirmativas en términos de género': 'equidad_acciones_afirm',
    'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se dedica tiempo de la clase a hacer reflexiones sobre equidad de género, por ejemplo, destacando los aportes de personajes masculinos y femeninos': 'equidad_reflexion',
    'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Se hace uso de lenguaje inclusivo, sin estereotipos de género, que promueva respeto por la diversidad': 'equidad_lenguaje_inc',
    'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - No se observa ninguna práctica pedagógica en pro de la equidad de género': 'equidad_ninguna',
    'Prácticas en pro de la equidad de género Elija todas las opciones que representen lo que haya sucedido durante la clase acompañada. - Otra': 'equidad_otra',
    'Otra.2': 'equidad_otra_detalle',
    'Por favor, agregue cualquier otra información adicional que considere relevante para aclarar sus respuestas a la pregunta anterior': 'info_adicional_equidad',
    'Instantánea 1 - minuto 8 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.': 'accion_docente',
    'Indique con quiénes está interactuando el/la docente': 'interaccion',
    '¿Con quiénes está interactuando el/la docente?': 'interaccion_det',
    '¿Están los/las estudiantes respondiendo las preguntas y/o participando en las discusiones?': 'participacion',
    '¿Están los/las estudiantes escuchando atentamente al docente?': 'escucha',
    '¿Están los/las estudiantes tomando nota de las explicaciones o discusiones?': 'notas',
    '¿Están los/las estudiantes haciendo preguntas y/o pidiendo ayuda al docente?': 'preguntas',
    '¿Están los/las estudiantes socializando su trabajo?': 'socializacion',
    '¿Quiénes están socializando su trabajo?': 'socializacion_quien',
    '¿Están los/las estudiantes distraídos, haciendo indisciplina o mostrando de alguna otra manera que no están involucrados en las actividades que lidera el/la docente?': 'distraccion',
    '¿Quiénes no están involucrados en las actividades que lidera el/la docente?': 'no_involucrados',
    '¿Están haciendo uso de herramientas computacionales?': 'uso_tech',
    '¿Quiénes están haciendo uso de herramientas computacionales?': 'uso_tech_quien',
    '¿Están los/las estudiantes trabajando individualmente?': 'trabajo_ind',
    '¿Están los/las estudiantes trabajando en parejas o grupos?': 'trabajo_grupo',
    '¿Quiénes están ejerciendo roles de liderazgo en el trabajo en parejas o grupos?': 'liderazgo',
    '¿Están los/las estudiantes realizando las actividades por sí mismos, sin ayuda del docente?': 'autonomia',
    'Agregue cualquier comentario adicional, que sea relevante para entender lo que está sucediendo en el aula en este instante de la clase': 'comentarios',
    '¿Avanzar a la Instantánea 2?': 'avanzar',
    'Por favor, seleccione qué desea hacer.': 'accion_final',
    'Ciudadanía digital y comprensión y uso de la IA ¿Se observan prácticas que busquen fomentar habilidades de ciudadanía digital o promover la comprensión y el uso de la IA? Marque sí si en la clase los/las estudiantes aprenden conceptos básicos de Inteligencia Artificial (IA, aprendizaje automático, modelo, algoritmo de aprendizaje, datos de entrenamiento, predicción, sesgos, etc.), realizan actividades desconectadas o conectadas de IA, o analizan problemas de seguridad, éticos y de sesgos asociados al uso de la tecnología con o sin IA.': 'ia_practicas_presentes',
    'Ciudadanía digital y comprensión y uso de la IA Responda todas las preguntas y luego, si es posible, describa brevemente la actividad que se realizó durante la clase y que permitió evidenciar el acercamiento a la comprensión y uso de la Inteligencia Artificial por parte de los/las estudiantes. ¿Los/las estudiantes llevan a cabo alguna actividad desconectada para fortalecer su comprensión de conceptos de IA? Ejemplo: analizar aplicaciones u objetos y decidir si corresponden o no a ejemplos de IA, etiquetar imágenes y luego discutir sesgos en la interpretación de estas, determinar los datos de entrenamiento requeridos para alguna toma de decisión o predicción, etc).': 'ia_act_desconectada_desc',
    '¿Los/las estudiantes usan herramientas de IA generativa? Ejemplo: hacen una consulta a un modelo grande de lenguaje como ChatGPT, crean imágenes mediante un prompt en Copilot o Meta, generan un video con Canva, etc.': 'ia_herramientas_generativas',
    '¿Los/las estudiantes entrenan modelos de IA o hacen uso de uno de estos modelos? Ejemplo: crean un modelo de reconocimiento de imágenes con TeachableMachine, crean un modelo de reconocimiento de texto con https://machinelearningforkids.co.uk/, vinculan un modelo de IA creado a un programa de Scratch o vinculan un proyecto en MakeCode con un modelo de IA usando https://makeairobots.com/, etc.': 'ia_entrenamiento_modelos',
    '¿Se realizan discusiones críticas sobre perspectiva, sesgos algorítmicos, o la necesidad de que población diversa contribuya en proyectos computacionales? Ejemplo: se analizan las fallas de un modelo de IA para reconocer una imagen, se discute por qué un modelo de IA genera imágenes que representan un estereotipo, se comentan las ventajas de que varias personas distintas colaboren para entrenar un modelo de IA, etc': 'ia_discusiones_criticas',
    '¿Se discuten o promueven buenas prácticas de seguridad digital (ej. la protección de datos, contraseñas, y el uso seguro de internet)?': 'ia_seguridad_digital',
    '¿Se abordan aspectos éticos del uso de tecnologías digitales (ej. respeto a la privacidad, uso responsable de la información)?': 'ia_etica_tecnologia',
    'Por favor, mencione las actividades asociadas a ciudadanía digital (seguridad informática, uso ético de tecnologías, equidad ) y/o de IA que se hayan desarrollado en la clase acompañada.': 'ia_actividades_desc'
}

In [100]:
def rename_columns(df, rename_dict):
    """
    Renombra las columnas de un DataFrame usando un diccionario.
    - Ignora claves en rename_dict que no coincidan con columnas existentes.
    - Mantiene los nombres originales si no hay nuevo nombre en rename_dict.

    Args:
        df (pandas.DataFrame): DataFrame cuyas columnas se van a renombrar.
        rename_dict (dict): Diccionario con {nombre_actual: nuevo_nombre}.

    Returns:
        pandas.DataFrame: DataFrame con las columnas renombradas.
    """
    # Crea una copia del DataFrame para evitar modificar el original
    df_renamed = df.copy()

    # Obtiene las columnas actuales del DataFrame
    current_columns = df_renamed.columns.tolist()


    # Solo incluye pares donde la clave está en las columnas actuales
    safe_rename_dict = {col: rename_dict[col] for col in current_columns if col in rename_dict}

    # Aplica el renombramiento
    df_renamed = df_renamed.rename(columns=safe_rename_dict)

    return df_renamed

In [101]:
[c for c in df.columns if 'meta' in c]

['¿Se promueven los procesos de metacognición y reflexión?']

In [102]:
# Obtiene todas las columnas hasta la columna de interés
columnas_hasta_instantanea = df.columns[:df.columns.get_loc('Instantánea 1 - minuto 8 de la observación ¿Qué está haciendo el/la docente ahora? Indique cuál de las siguientes acciones es la principal que está realizando la/el docente en este instante.') + 1]


columnas_a_seleccionar = columnas_hasta_instantanea.to_list() + ['Visita', 'Momento', '¿Se promueven los procesos de metacognición y reflexión?', 'Al cierre de la clase ¿Se hace uso de algún tipo de gráfico de anclaje o memoria colectiva?']

# Selecciona las columnas para crear Obs_generales
obs_generales = df.loc[:, columnas_a_seleccionar].copy()

In [103]:
# Llama a la función
instantaneas = rename_columns(instantaneas, rename_dict)
obs_generales = rename_columns(obs_generales, rename_dict)

In [104]:
instantaneas["¿Qué está haciendo el/la docente ahora?"].unique()

array(['Está dando una explicación temática',
       'Está haciendo actividades de gestión de aula (disciplina, atención de los/las estudiantes, etc)',
       'Está haciendo preguntas a los/las estudiantes',
       'Está dando instrucciones para el desarrollo de una actividad',
       'Está monitoreando o supervisando el trabajo de los/las estudiantes, sin intervenir',
       'Está escuchando las intervenciones o presentaciones de los/las estudiantes',
       'Está retroalimentando el trabajo realizado por los/las estudiantes',
       nan, 'Está hablando de temas no relacionados con la clase'],
      dtype=object)

In [105]:
instantaneas = instantaneas.replace(['nan', 'NaN', 'N/A'], '', regex=False)
obs_generales = obs_generales.replace(['nan', 'NaN', 'N/A'], '', regex=False)

C:\Users\maria\AppData\Local\Temp\ipykernel_24376\4285620766.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  obs_generales = obs_generales.replace(['nan', 'NaN', 'N/A'], '', regex=False)

In [106]:
nuevo_orden = [
    # Metadatos generales y fechas
    'fecha_inicio',
    'fecha_fin',
    'visita',
    'momento',

    'fecha_acomp',
    'fecha_registro',
    'hora_inicio',
    'duracion_clase',
    'duracion_seg',

    # Identificación y datos del docente
    'doc_docente',
    'nombre_docente',
    'sexo_docente',
    'unidad',
    'mentor',
    'Código',

    # Respuesta y progreso
    'tipo_respuesta',
    'id_respuesta',
    'ip',
    'progreso',
    'finalizado',

    # Ubicación y distribución
    'latitud',
    'longitud',
    'canal_dist',
    'idioma',

    # Detalles de la clase
    'asignatura',
    'Asignatura - Otra - Texto',
    'grado',
    'guia_pedagogica',
    'grado_guia',
    'num_guia',
    'sesion_guia',
    'tema_clase',
    'total_estudiantes',
    'est_femenino',
    'est_masculino',

    # Tecnologías digitales
    'tech_portatiles',
    'tech_escritorio',
    'tech_tabletas',
    'tech_celulares',
    'tech_microbit',
    'tech_proyector',
    'tech_ninguna',
    'tech_otra',
    'tech_otra_detalle',

    # Interacciones y timing
    'click_inicio',
    'click_fin',
    'envio_pagina',
    'num_clics',
    'min_inicio_gestion',
    'objetivos_aprend',
    'conoc_previos',
    'conceptos_clave',

    # Competencias computacionales
    'subhabilidades_comp',
    'descomposicion',
    'patrones',
    'algoritmico',
    'depuracion',
    'abstraccion',
    'logico',
    'actividades_comp',
    'practicas_datos',
    'recoleccion_datos',
    'patrones_datos',
    'organizacion_datos',
    'visualizacion_datos',
    'actividades_datos',
    'practicas_programacion',
    'descomposicion_prog',
    'instrucciones_prog',
    'codificacion',
    'depuracion_prog',
    'actividades_programacion',
    'simulaciones',
    'uso_simuladores',
    'evaluacion_simulaciones',
    'actividades_simulaciones',
    'pensamiento_sistemico',
    'datos_numericos',
    'relaciones_numericas',
    'impacto_variables',
    'actividades_sistemico',

    # Actividades relacionadas con IA y ciudadanía digital
    'ia_practicas_presentes',
    'ia_act_desconectada_desc',
    'ia_herramientas_generativas',
    'ia_entrenamiento_modelos',
    'ia_discusiones_criticas',
    'ia_seguridad_digital',
    'ia_etica_tecnologia',
    'ia_actividades_desc',

    # Habilidades y resolución
    'vocabulario_comp',
    'conexion_vida',
    'resolucion_tecnica',
    'dificultades_tecnicas',

    # Gestión y preparación
    'prep_material',
    'gestion_material',
    'valoracion_esfuerzo',
    'apoyo_estudiantes',

    # Equidad y diversidad
    'equidad_corrige_sexismo',
    'equidad_liderazgo_fem',
    'equidad_acciones_afirm',
    'equidad_reflexion',
    'equidad_lenguaje_inc',
    'equidad_ninguna',
    'equidad_otra',
    'otra_asignatura',
    'info_adicional_equidad',
    'metacognicion',
    'uso_grafico_anclaje',
]

In [107]:
obs_generales = obs_generales.reindex(columns=nuevo_orden)

In [108]:
instantaneas['¿Qué está haciendo el/la docente ahora?'].unique()

array(['Está dando una explicación temática',
       'Está haciendo actividades de gestión de aula (disciplina, atención de los/las estudiantes, etc)',
       'Está haciendo preguntas a los/las estudiantes',
       'Está dando instrucciones para el desarrollo de una actividad',
       'Está monitoreando o supervisando el trabajo de los/las estudiantes, sin intervenir',
       'Está escuchando las intervenciones o presentaciones de los/las estudiantes',
       'Está retroalimentando el trabajo realizado por los/las estudiantes',
       nan, 'Está hablando de temas no relacionados con la clase'],
      dtype=object)

In [109]:
['Está explicando conceptos de pensamiento computacional y/o programación',
       'Está haciendo preguntas a toda la clase',
       'Está dando instrucciones para el desarrollo de una actividad',
       'Está monitoreando o supervisando el trabajo de los/las estudiantes, sin intervenir',
       'Está copiando en el tablero sin hablar',
       'Está escuchando las intervenciones o presentaciones de los/las estudiantes',
       'Está retroalimentando el trabajo realizado por los/las estudiantes (en parejas o grupos)',
       'Está resolviendo problemas técnicos (uso del proyector, problemas con el computador, etc)',
       'Está haciendo actividades de gestión de aula (disciplina, atención de los/las estudiantes, etc)',
       'Está explicando conceptos relevantes para la lección, pero no asociados al pensamiento computacional o la programación',
       'Está presente físicamente, pero desconectado(a) de las actividades',
       'Está hablando de temas no relacionados con la clase',
       'Está ausente físicamente',
       'Está dando instrucciones para la próxima clase'],

['Está dando instrucciones para el desarrollo de una actividad',
       'Está dando una explicación temática',
       'Está haciendo preguntas a los/las estudiantes',
       'Está haciendo actividades de gestión de aula (disciplina, atención de los/las estudiantes, etc)',
       'Está resolviendo problemas técnicos (uso del proyector, problemas con el computador, etc)',
       'Está presente físicamente, pero desconectado(a) de las actividades',
       'Está copiando en el tablero sin hablar',
       'Está monitoreando o supervisando el trabajo de los/las estudiantes, sin intervenir',
       'Está escuchando las intervenciones o presentaciones de los/las estudiantes',
       'Está hablando de temas no relacionados con la clase',
       'Está retroalimentando el trabajo realizado por los/las estudiantes',
       'Está aclarando dudas no relacionadas con instrucciones de actividades',
       'Está ausente físicamente',
       'Está dando instrucciones para la próxima clase']

docente_actividades = {
    "Instrucción docente": [
        {"full_name": "Está explicando conceptos de pensamiento computacional y/o programación", "clean_name": "Conceptos de PC"},
        {"full_name": "Está explicando conceptos relevantes para la lección, pero no asociados al pensamiento computacional o la programación", "clean_name": "Conceptos relevantes, no de PC"},
        {"full_name": "Está dando instrucciones para el desarrollo de una actividad", "clean_name": "Dar instrucciones"},
        {"full_name": "Está dando una explicación temática", "clean_name": "Explicar temas"},
        {"full_name": "Está copiando en el tablero sin hablar", "clean_name": "Copiar en tablero"},
    ],
    "Interacción": [
        {"full_name": "Está escuchando las intervenciones o presentaciones de los/las estudiantes", "clean_name": "Escuchar intervenciones"},
        {"full_name": "Está monitoreando o supervisando el trabajo de los/las estudiantes, sin intervenir", "clean_name": "Supervisar trabajos"},
        {"full_name": "Está haciendo preguntas a los/las estudiantes", "clean_name": "Hacer preguntas"},
        {"full_name": "Está retroalimentando el trabajo realizado por los/las estudiantes", "clean_name": "Retroalimentar trabajos"},
        {"full_name": "Está aclarando dudas no relacionadas con instrucciones de actividades", "clean_name": "Aclarar dudas"},
    ],
    "Gestión de aula": [
        {"full_name": "Está haciendo actividades de gestión de aula (disciplina, atención de los/las estudiantes, etc)", "clean_name": "Gestión de aula"},
        {"full_name": "Está resolviendo problemas técnicos (uso del proyector, problemas con el computador, etc)", "clean_name": "Resolver problemas técnicos"},
    ],
    "Tareas no docente": [
        {"full_name": "Está ausente físicamente", "clean_name": "Ausente físicamente"},
        {"full_name": "Está presente físicamente, pero desconectado(a) de las actividades", "clean_name": "Desconectado de actividades"},
        {"full_name": "Está hablando de temas no relacionados con la clase", "clean_name": "Temas no relacionados"},
        {"full_name": "Está dando instrucciones para la próxima clase", "clean_name": "Instrucciones próxima clase"},
    ],
}

actividad_map = {x["full_name"]: {"clean": x["clean_name"], "cat": categoria} for categoria, valores in docente_actividades.items() for x in valores}

In [110]:
instantaneas

,id_respuesta,Número de instantánea,momento,visita,doc_docente,sexo_docente,guia_pedagogica,asignatura,Codigo,¿Qué está haciendo el/la docente ahora?,...,socializacion_quien,distraccion,no_involucrados,uso_tech,uso_tech_quien,trabajo_ind,trabajo_grupo,liderazgo,autonomia,comentarios
0,R_5iF6jTr3hvUIYHT,1,Post,2,1.028796e+07,Hombre,Sí,Física,NaN,Está dando una explicación temática,...,NaN,Ninguno,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,En este momento se encuentra el docente presen...
1,R_7Oe7ZAcrnQzWtoh,1,Post,2,2.443666e+07,Mujer,No,Matemáticas,NaN,Está haciendo actividades de gestión de aula (...,...,NaN,La mayoría,Niños y niñas por igual,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,La docente se encuetnra llamando la atención a...
2,R_31dqVm3EeEdIJqi,1,Post,2,3.073847e+07,Mujer,No,Matemáticas,NaN,Está haciendo preguntas a los/las estudiantes,...,NaN,Ninguno,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,La docente esta conectgando el nuevo conocimin...
3,R_310nLwVtnbAjLFy,1,Post,2,7.506251e+07,Hombre,No,Matemáticas,NaN,Está dando una explicación temática,...,NaN,Ninguno,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,En este omento el docente se encuentra present...
4,R_7X70SCcie932mQx,1,Post,2,1.053781e+09,Hombre,No,Física,NaN,Está dando una explicación temática,...,NaN,Ninguno,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,El docente se encuentra presentando el objetiv...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,R_7Oe7ZAcrnQzWtoh,12,Post,2,2.443666e+07,Mujer,No,Matemáticas,NaN,Está haciendo preguntas a los/las estudiantes,...,NaN,Ninguno,NaN,Ninguno,NaN,Ninguno,Todos(as),Niños y niñas por igual,Ninguno,La docente esa lanzando la pregunta a los estu...
2,R_31dqVm3EeEdIJqi,12,Post,2,3.073847e+07,Mujer,No,Matemáticas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,R_310nLwVtnbAjLFy,12,Post,2,7.506251e+07,Hombre,No,Matemáticas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,R_7X70SCcie932mQx,12,Post,2,1.053781e+09,Hombre,No,Física,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,R_1EWNOwR7k9SdwrL,12,Post,2,1.053818e+09,Hombre,No,Física,NaN,Está escuchando las intervenciones o presentac...,...,Niños y niñas por igual,Ninguno,NaN,Ninguno,NaN,Ninguno,Todos(as),No se evidencian roles de liderazgo,Ninguno,Un representante de cada grupo se encuetnra so...

In [111]:
# Mapeo instantáneas
def map_actividad(actividad):
    if actividad in actividad_map:
        return actividad_map[actividad]["clean"], actividad_map[actividad]["cat"]
    else:
        return actividad, None

instantaneas[['accion_docente_clean', 'accion_docente_cat']] = instantaneas['¿Qué está haciendo el/la docente ahora?'].apply(lambda x: pd.Series(map_actividad(x)))

In [112]:
instantaneas

,id_respuesta,Número de instantánea,momento,visita,doc_docente,sexo_docente,guia_pedagogica,asignatura,Codigo,¿Qué está haciendo el/la docente ahora?,...,no_involucrados,uso_tech,uso_tech_quien,trabajo_ind,trabajo_grupo,liderazgo,autonomia,comentarios,accion_docente_clean,accion_docente_cat
0,R_5iF6jTr3hvUIYHT,1,Post,2,1.028796e+07,Hombre,Sí,Física,NaN,Está dando una explicación temática,...,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,En este momento se encuentra el docente presen...,Explicar temas,Instrucción docente
1,R_7Oe7ZAcrnQzWtoh,1,Post,2,2.443666e+07,Mujer,No,Matemáticas,NaN,Está haciendo actividades de gestión de aula (...,...,Niños y niñas por igual,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,La docente se encuetnra llamando la atención a...,Gestión de aula,Gestión de aula
2,R_31dqVm3EeEdIJqi,1,Post,2,3.073847e+07,Mujer,No,Matemáticas,NaN,Está haciendo preguntas a los/las estudiantes,...,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,La docente esta conectgando el nuevo conocimin...,Hacer preguntas,Interacción
3,R_310nLwVtnbAjLFy,1,Post,2,7.506251e+07,Hombre,No,Matemáticas,NaN,Está dando una explicación temática,...,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,En este omento el docente se encuentra present...,Explicar temas,Instrucción docente
4,R_7X70SCcie932mQx,1,Post,2,1.053781e+09,Hombre,No,Física,NaN,Está dando una explicación temática,...,NaN,Ninguno,NaN,Todos(as),Ninguno,NaN,Ninguno,El docente se encuentra presentando el objetiv...,Explicar temas,Instrucción docente
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,R_7Oe7ZAcrnQzWtoh,12,Post,2,2.443666e+07,Mujer,No,Matemáticas,NaN,Está haciendo preguntas a los/las estudiantes,...,NaN,Ninguno,NaN,Ninguno,Todos(as),Niños y niñas por igual,Ninguno,La docente esa lanzando la pregunta a los estu...,Hacer preguntas,Interacción
2,R_31dqVm3EeEdIJqi,12,Post,2,3.073847e+07,Mujer,No,Matemáticas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,R_310nLwVtnbAjLFy,12,Post,2,7.506251e+07,Hombre,No,Matemáticas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,R_7X70SCcie932mQx,12,Post,2,1.053781e+09,Hombre,No,Física,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,R_1EWNOwR7k9SdwrL,12,Post,2,1.053818e+09,Hombre,No,Física,NaN,Está escuchando las intervenciones o presentac...,...,NaN,Ninguno,NaN,Ninguno,Todos(as),No se evidencian roles de liderazgo,Ninguno,Un representante de cada grupo se encuetnra so...,Escuchar intervenciones,Interacción

In [113]:
# # Asignar 'momento' como 'Pre' para la primera visita y 'Post' para la segunda visita por cada docente
# instantaneas = instantaneas.sort_values(['doc_docente', 'visita'])
# instantaneas['visita_order'] = instantaneas.groupby('doc_docente')['visita'].rank(method='dense').astype('Int64')
# instantaneas['momento'] = instantaneas['visita_order'].map({1: 'Pre', 2: 'Post'})
# instantaneas = instantaneas.drop(columns=['visita_order'])
# # Mostrar los primeros registros para verificar
# instantaneas

In [114]:
!pip install plotly
import plotly.express as px

Requirement already satisfied: plotly in c:\users\maria\github_marianaarboleda\cp_backend\.conda\lib\site-packages (6.5.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\maria\github_marianaarboleda\cp_backend\.conda\lib\site-packages (from plotly) (2.13.0)
Requirement already satisfied: packaging in c:\users\maria\github_marianaarboleda\cp_backend\.conda\lib\site-packages (from plotly) (25.0)

In [115]:
# Porcentaje de cada categoría por Momento e Instantánea, líneas que muestran el porcentaje de cada categoría para esa instantánea (cada instantánea suma 100%, el color de la línea es la categoría)
# Dividir en dos gráficos, uno para Pre y otro para Post

import plotly.express as px
import pandas as pd

# Assuming final_df_activities is already loaded
# Remove missing categories
df = instantaneas.dropna(subset=["accion_docente_cat"])

# Count how many occurrences of each category per instant and moment
df_counts = (
    df.groupby(["momento", "Número de instantánea", "accion_docente_cat"])
    .size()
    .reset_index(name="count")
)

# Calculate percentages per instant within each moment
df_counts["percent"] = (
    df_counts.groupby(["momento", "Número de instantánea"])["count"]
    .apply(lambda x: 100 * x / x.sum())
    .reset_index(drop=True)
)

# Split into two datasets
for momento in df_counts["momento"].unique():
    df_momento = df_counts[df_counts["momento"] == momento]

    fig = px.line(
        df_momento,
        x="Número de instantánea",
        y="percent",
        color="accion_docente_cat",
        markers=True,
        title=f"Distribución porcentual de categorías - {momento}",
        labels={"percent": "Porcentaje (%)", "Número de instantánea": "Número de instantánea"}
    )

    fig.update_layout(
        yaxis=dict(range=[0, 100]),
        legend_title_text="Categoría",
        template="plotly_white",
    )

    fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [116]:
import pandas as pd
import plotly.express as px

# --- Prepare data ---
df_heat = instantaneas.copy()

# Ensure numeric and clean
df_heat['Número de instantánea'] = pd.to_numeric(df_heat['Número de instantánea'], errors='coerce')
df_heat = df_heat.dropna(subset=['Número de instantánea', 'accion_docente_clean'])

# Calculate percentages per instantánea and momento
df_counts = (
    df_heat.groupby(['momento', 'Número de instantánea', 'accion_docente_clean'])
    .size()
    .reset_index(name='count')
)

df_counts['percent'] = (
    df_counts.groupby(['momento', 'Número de instantánea'])['count']
    .apply(lambda x: 100 * x / x.sum())
    .reset_index(drop=True)
)

# Keep consistent y order by overall frequency
ordered_actions = df_counts['accion_docente_clean'].value_counts().index.tolist()
df_counts['accion_docente_clean'] = pd.Categorical(df_counts['accion_docente_clean'], categories=ordered_actions, ordered=True)

# --- Create pivot tables per momento ---
pivot_pre = df_counts[df_counts['momento'] == 'Pre'].pivot(index='accion_docente_clean', columns='Número de instantánea', values='percent')
pivot_post = df_counts[df_counts['momento'] == 'Post'].pivot(index='accion_docente_clean', columns='Número de instantánea', values='percent')

# --- Define same color scale as before (replace if needed) ---
color_scale = "Purples"

pivot_pre = pivot_pre.fillna(0)
pivot_post = pivot_post.fillna(0)

for momento in ["Pre", "Post"]:
    if momento == "Pre":
        data = pivot_pre
    else:
        data = pivot_post

    # --- Create side-by-side heatmaps (facets manually) ---
    fig = px.imshow(
        data,
        labels=dict(x="Número de instantánea", y="Acción del docente", color="Porcentaje"),
        x=data.columns,
        color_continuous_scale=color_scale,
        text_auto=".1f"
    )

    fig.update_layout(
        title=f"¿Qué está haciendo el docente? (Distribución porcentual por instantánea) - {momento}",
        height=850,
        margin=dict(l=280, r=40, t=80, b=40),
        coloraxis_colorbar=dict(title="Porcentaje"),
        template="plotly_white",
    )

    fig.update_traces(
        texttemplate="%{z:0.1f}%",
        hovertemplate="Acción: %{y}<br>Momento/Inst: %{x}<br>%{z:.1f}%<extra></extra>",
        textfont=dict(size=8),
    )

    fig.update_yaxes(autorange="reversed")

    fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [117]:
obs_generales.to_csv('../data/limpieza/obs_generales_stem_limpio_post.csv', index=False)
instantaneas.to_csv('../data/limpieza/instantaneas_stem_limpio_post.csv', index=False)

In [118]:
obs_generales.columns.to_list()

['fecha_inicio',
 'fecha_fin',
 'visita',
 'momento',
 'fecha_acomp',
 'fecha_registro',
 'hora_inicio',
 'duracion_clase',
 'duracion_seg',
 'doc_docente',
 'nombre_docente',
 'sexo_docente',
 'unidad',
 'mentor',
 'Código',
 'tipo_respuesta',
 'id_respuesta',
 'ip',
 'progreso',
 'finalizado',
 'latitud',
 'longitud',
 'canal_dist',
 'idioma',
 'asignatura',
 'Asignatura - Otra - Texto',
 'grado',
 'guia_pedagogica',
 'grado_guia',
 'num_guia',
 'sesion_guia',
 'tema_clase',
 'total_estudiantes',
 'est_femenino',
 'est_masculino',
 'tech_portatiles',
 'tech_escritorio',
 'tech_tabletas',
 'tech_celulares',
 'tech_microbit',
 'tech_proyector',
 'tech_ninguna',
 'tech_otra',
 'tech_otra_detalle',
 'click_inicio',
 'click_fin',
 'envio_pagina',
 'num_clics',
 'min_inicio_gestion',
 'objetivos_aprend',
 'conoc_previos',
 'conceptos_clave',
 'subhabilidades_comp',
 'descomposicion',
 'patrones',
 'algoritmico',
 'depuracion',
 'abstraccion',
 'logico',
 'actividades_comp',
 'practicas_datos',
 'recoleccion_datos',
 'patrones_datos',
 'organizacion_datos',
 'visualizacion_datos',
 'actividades_datos',
 'practicas_programacion',
 'descomposicion_prog',
 'instrucciones_prog',
 'codificacion',
 'depuracion_prog',
 'actividades_programacion',
 'simulaciones',
 'uso_simuladores',
 'evaluacion_simulaciones',
 'actividades_simulaciones',
 'pensamiento_sistemico',
 'datos_numericos',
 'relaciones_numericas',
 'impacto_variables',
 'actividades_sistemico',
 'ia_practicas_presentes',
 'ia_act_desconectada_desc',
 'ia_herramientas_generativas',
 'ia_entrenamiento_modelos',
 'ia_discusiones_criticas',
 'ia_seguridad_digital',
 'ia_etica_tecnologia',
 'ia_actividades_desc',
 'vocabulario_comp',
 'conexion_vida',
 'resolucion_tecnica',
 'dificultades_tecnicas',
 'prep_material',
 'gestion_material',
 'valoracion_esfuerzo',
 'apoyo_estudiantes',
 'equidad_corrige_sexismo',
 'equidad_liderazgo_fem',
 'equidad_acciones_afirm',
 'equidad_reflexion',
 'equidad_lenguaje_inc',
 'equidad_ninguna',
 'equidad_otra',
 'otra_asignatura',
 'info_adicional_equidad',
 'metacognicion',
 'uso_grafico_anclaje']

In [37]:
import plotly.graph_objects as go


objetivos_map ={
    'objetivos_aprend': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Objetivos de Aprendizaje', 'category': 'Inicio de clase'},
    'conoc_previos': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Conocimientos Previos', 'category': 'Inicio de clase'},
    'conceptos_clave': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Conceptos Clave', 'category': 'Inicio de clase'},
    'vocabulario_comp': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Vocabulario adecuado', 'category': 'Conocimientos técnicos'},
    'conexion_vida': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Conexión con la vida diaria', 'category': 'Conocimientos técnicos'},
    'prep_material': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Preparación de materiales', 'category': 'Prácticas pedagógicas y de gestión de aula'},
    'gestion_material': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Gestión de materiales', 'category': 'Prácticas pedagógicas y de gestión de aula'},
    'valoracion_esfuerzo': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Valoración del esfuerzo', 'category': 'Prácticas pedagógicas y de gestión de aula'},
    'apoyo_estudiantes': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Apoyo a estudiantes', 'category': 'Prácticas pedagógicas y de gestión de aula'},
    'metacognicion': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Metacognición y reflexión', 'category': 'Cierre de clase'},
    'uso_grafico_anclaje': {'positive_words': ['sí'], 'negative_words': ['no'], 'clean_name': 'Uso de gráfico de anclaje o memoria colectiva', 'category': 'Cierre de clase'},
}

clean_objetivos = obs_generales.copy()

def clean_column_values(value, positive_words, negative_words):

    if pd.isna(value):
        return 'No'
    value = value.lower().strip()
    if any(pos_word in value for pos_word in positive_words):
        return 'Sí'
    if any(neg_word in value for neg_word in negative_words):
        return 'No'
    return 'No'


# clean column values
for col, mapping in objetivos_map.items():
    clean_objetivos[col] = clean_objetivos[col].str.lower().str.strip()
    clean_objetivos[col] = clean_objetivos [col].fillna('No')
    clean_objetivos[col] = clean_objetivos[col].apply(lambda x: clean_column_values(x, mapping['positive_words'], mapping['negative_words']))

In [38]:
for col, mapping in objetivos_map.items():
    for momento in ['Pre', 'Post']:
        mask = clean_objetivos['momento'] == momento
        pos_count = (clean_objetivos.loc[mask, col] == 'Sí').sum()
        neg_count = (clean_objetivos.loc[mask, col] == 'No').sum()
        total = pos_count + neg_count
        percentage = (pos_count / total * 100) if total > 0 else 0
        key = 'pre_percentage' if momento == 'Pre' else 'post_percentage'
        objetivos_map[col][key] = percentage

# Data grouped by section
# groups = {
#     'Inicio de clase': [
#         ('Objetivos de aprendizaje', 42, 89),
#         ('Conocimientos previos', 62, 88),
#         ('Conceptos clave', 70, 91)
#     ],
#     'Conocimientos técnicos': [
#         ('Vocabulario adecuado', 73, 91),
#         ('Conexión vida diaria', 42, 80)
#     ],
#     'Prácticas pedagógicas y de gestión de aula': [
#         ('Material preparado', 56, 86),
#         ('Gestión de materiales', 58, 82),
#         ('Valoración esfuerzo', 59, 80),
#         ('Estrategias de apoyo', 59, 74)
#     ],
#     'Cierre de la clase': [
#         ('Gráficos de anclaje', 8, 36),
#         ('Metacognición', 27, 74)
#     ]
# }

# Flatten data for plotting and record section starts
categories = []
pretest = []
posttest = []
section_starts = []
sections = []

# for section, items in groups.items():
#     section_starts.append(len(categories))
#     for cat, pre, post in items:
#         sections.append(section)
#         categories.append(cat)
#         pretest.append(pre)
#         posttest.append(post)


for col, mapping in objetivos_map.items():
    sections.append(mapping['category'])
    categories.append(mapping['clean_name'])
    pretest.append(mapping['pre_percentage'])
    posttest.append(mapping['post_percentage'])
    if mapping['category'] not in section_starts:
        section_starts.append(len(categories) - 1)



# Create figure
fig = go.Figure()

# Add connecting lines
for i in range(len(categories)):
    fig.add_trace(go.Scatter(
        x=[pretest[i], posttest[i]],
        y=[[sections[i], sections[i]], [categories[i], categories[i]]],
        mode='markers+lines',
        line=dict(color='lightgray', width=2),
        showlegend=False
    ))

full_sections = []

for section in sections:
    full_sections.append(section)
    full_sections.append(section)

# Add pretest and posttest markers + labels
fig.add_trace(go.Scatter(
    x=pretest, y=[sections, categories], mode='markers+text',
    name='Pretest', marker=dict(color='cornflowerblue', size=10),
    text=[f'{v:.1f}%' for v in pretest], textposition='middle left'
))

fig.add_trace(go.Scatter(
    x=posttest, y=[sections, categories], mode='markers+text',
    name='Postest', marker=dict(color='orchid', size=10),
    text=[f'{v:.1f}%' for v in posttest], textposition='middle right'
))


# Layout: reverse y to keep provided order top->bottom, increase left margin
fig.update_layout(
    title='Porcentaje de docentes observados en cada práctica',
    xaxis_title='Docentes observados',
    xaxis=dict(range=[0, 100], ticksuffix='%'),
    template='simple_white',
    height=700,
    yaxis_title='',
    yaxis=dict(autorange='reversed'),  # keep categories in the order we defined
    margin=dict(l=300, r=20, t=60, b=50),
    legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
)

fig.show()